### ISSUE TITLE
Home Assistant wont load with HACS post update to v 0.8

### ISSUE THREAD

**Issue by mokshmridul** [custom-components/hacs#107]
Version: 0.8.0

Desription: Home Assistant wont load after updating it to Version 0.8.0 from v0.7.0 

```text



Traceback (most recent call last):


  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main


    "__main__", mod_spec)


  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code


    exec(code, run_globals)


  File "/usr/src/homeassistant/homeassistant/__main__.py", line 404, in <module>


    sys.exit(main())


  File "/usr/src/homeassistant/homeassistant/__main__.py", line 396, in main


    exit_code = asyncio_run(setup_and_run_hass(config_dir, args))


  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run


    return loop.run_until_complete(main)


  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete


  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete


  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever


  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run


  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle


  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run


  File "/config/custom_components/hacs/hacsbase.py", line 56, in startup_tasks


    repository = await self.aiogithub.get_repo("custom-components/hacs")


  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry


    ret = await target(*args, **kwargs)


  File "/config/custom_components/hacs/aiogithub.py", line 61, in get_repo


    raise AIOGitHubException(response["message"])


custom_components.hacs.aiogithub.AIOGitHubException: API rate limit exceeded for user ID 8089422.


Exception in thread zeroconf-ServiceBrowser__esphomelib._tcp.local.:


Traceback (most recent call last):


  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner


    self.run()


  File "/usr/local/lib/python3.7/site-packages/zeroconf.py", line 1423, in run


    handler(self.zc)


  File "/usr/local/lib/python3.7/site-packages/zeroconf.py", line 1363, in <lambda>


    zeroconf=zeroconf, service_type=self.type, name=name, state_change=state_change


  File "/usr/local/lib/python3.7/site-packages/zeroconf.py", line 1250, in fire


    h(**kwargs)


  File "/usr/src/homeassistant/homeassistant/components/zeroconf/__init__.py", line 78, in service_update


    domain, context={'source': DOMAIN}, data=info


  File "/usr/src/homeassistant/homeassistant/core.py", line 255, in add_job


    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)


  File "uvloop/loop.pyx", line 1261, in uvloop.loop.Loop.call_soon_threadsafe


  File "uvloop/loop.pyx", line 604, in uvloop.loop.Loop._call_soon


  File "uvloop/loop.pyx", line 608, in uvloop.loop.Loop._call_soon_handle


  File "uvloop/loop.pyx", line 637, in uvloop.loop.Loop._check_closed


RuntimeError: Event loop is closed




/usr/local/lib/python3.7/threading.py:951: RuntimeWarning: coroutine 'FlowManager.async_init' was never awaited


  del exc_type, exc_value, exc_tb


RuntimeWarning: Enable tracemalloc to get the object allocation traceback

```

**Comment by mokshmridul** [comment]
Note: Problem goes away, if the Github API Token is deleted and regenerated.

**Comment by ludeeus** [comment]
It also goes away if you wait 1 hour

**Comment by mokshmridul** [comment]
Im guessing that means that I hit the Github API Limit?

I did restart HA about 5-6 times, but even then, is'int the API limit 5000/ hour?

**Comment by ludeeus** [comment]
The limit is 5000 yes.

The limit itself does not cause HA to halt, an unexcepted error does.
Fixed here <https://github.com/custom-components/hacs/commit/3aca35da2928b0da3a0d52d1c12d3f68b9ced369>
