### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by CiquattroFPV** [custom-components/hacs#134]
## Version of HACS

Version: 0.8.1

## Describe the bug

After installinc hacs and I click on the community tab it always display "Background task running, refresh the page in a little while"

## Debug log

```text

HACS (Home Assistant Community Store)
Version: 0.8.1
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/hacs/issues
-------------------------------------------------------------------

2019-06-19 16:46:27 [custom_components.hacs] 

2019-06-19 16:46:43 [homeassistant.core] Error doing job: Task exception was never retrieved

2019-06-19 16:46:43 [homeassistant.core] Error doing job: Task exception was never retrieved

2019-06-19 16:48:50 [homeassistant.core] Error doing job: Task exception was never retrieved

2019-06-19 16:48:50 [homeassistant.core] Error doing job: Task exception was never retrieved

2019-06-19 16:48:50 [homeassistant.core] Error doing job: Task exception was never retrieved

2019-06-19 16:48:50 [homeassistant.core] Error doing job: Task exception was never retrieved

2019-06-19 16:48:50 [homeassistant.core] Error doing job: Task exception was never retrieved

2019-06-19 16:48:50 [homeassistant.core] Error doing job: Task exception was never retrieved

2019-06-19 16:48:50 [homeassistant.core] Error doing job: Task exception was never retrieved

2019-06-19 16:48:50 [homeassistant.core] Error doing job: Task exception was never retrieved

2019-06-19 16:48:50 [homeassistant.core] Error doing job: Task exception was never retrieved

2019-06-19 16:48:50 [homeassistant.core] Error doing job: Task exception was never retrieved

2019-06-19 16:48:50 [homeassistant.core] Error doing job: Task exception was never retrieved

2019-06-19 16:48:54 [custom_components.hacs.hacs] Runing startup tasks.

2019-06-19 16:49:24 [homeassistant.core] Error doing job: Task exception was never retrieved

2019-06-19 16:49:51 [custom_components.hacs.frontend] 'NoneType' object has no attribute 'pending_restart'

2019-06-19 16:49:53 [custom_components.hacs.frontend] GET API call for log with get

```

**Comment by ludeeus** [comment]
You have issues that are not displayed in that log. check your Home Assistant log file for more details.

**Comment by CiquattroFPV** [comment]
I have enabled the debug as stated in the logger documentation and restarted HA.. but it display only this logs on homeassistant.log

```
logger:
  #default: warn
  default: error
  logs:
    custom_components.hacs: debug
```

```

2019-06-19 16:49:51 ERROR (MainThread) [custom_components.hacs.frontend] 'NoneType' object has no attribute 'pending_restart'
2019-06-19 16:49:53 DEBUG (MainThread) [custom_components.hacs.frontend] GET API call for log with get
2019-06-19 16:50:54 ERROR (MainThread) [custom_components.hacs.frontend] 'NoneType' object has no attribute 'pending_restart'
2019-06-19 16:50:56 DEBUG (MainThread) [custom_components.hacs.frontend] GET API call for log with get
2019-06-19 16:51:37 ERROR (MainThread) [custom_components.hacs.frontend] 'NoneType' object has no attribute 'pending_restart'
2019-06-19 16:51:37 ERROR (MainThread) [custom_components.hacs.frontend] 'NoneType' object has no attribute 'pending_restart'
2019-06-19 16:51:38 DEBUG (MainThread) [custom_components.hacs.frontend] GET API call for log with get
2019-06-19 16:57:18 ERROR (MainThread) [custom_components.hacs.frontend] 'NoneType' object has no attribute 'pending_restart'
2019-06-19 16:57:19 DEBUG (MainThread) [custom_components.hacs.frontend] GET API call for log with get
```

**Comment by CiquattroFPV** [comment]
I found this log 

```

2019-06-19 16:49:24 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/aiogithub.py", line 53, in get_repo
    response = await self.session.get(url, headers=headers)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "uvloop/loop.pyx", line 1894, in create_connection
  File "uvloop/loop.pyx", line 1883, in uvloop.loop.Loop.create_connection
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase.py", line 56, in startup_tasks
    repository = await self.aiogithub.get_repo("custom-components/hacs")
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/config/custom_components/hacs/aiogithub.py", line 61, in get_repo
    raise AIOGitHubException(response["message"])
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
```

**Comment by ludeeus** [comment]
yeah..
GitHub have issues ATM.
I get the same on my install, try again later.

**Comment by CiquattroFPV** [comment]
oh so it's a temporary issue of github

**Comment by CiquattroFPV** [comment]
I'm still having problems

**Comment by ludeeus** [comment]
0.9.0 will have logic for retry if TimeoutError.
Can you try using the master branch?
You will get some undocumented features and a update notification for HACS (since you have a newer version)

**Comment by CiquattroFPV** [comment]
I still have some error on new version 0.9.0:



```
2019-06-20 10:34:24 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/aiogithub.py", line 53, in get_repo
    response = await self.session.get(url, headers=headers)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "uvloop/loop.pyx", line 1894, in create_connection
  File "uvloop/loop.pyx", line 1883, in uvloop.loop.Loop.create_connection
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase.py", line 57, in startup_tasks
    repository = await self.aiogithub.get_repo("custom-components/hacs")
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/config/custom_components/hacs/aiogithub.py", line 61, in get_repo
    raise AIOGitHubException(response["message"])
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
```

```
2019-06-20 10:33:11 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-06-20 10:33:18 INFO (MainThread) [custom_components.hacs] 
2019-06-20 10:34:44 ERROR (MainThread) [custom_components.hacs.frontend] 'NoneType' object has no attribute 'version_installed'
2019-06-20 10:34:45 DEBUG (MainThread) [custom_components.hacs.frontend] GET API call for log with get
2019-06-20 10:34:58 ERROR (MainThread) [custom_components.hacs.frontend] 'NoneType' object has no attribute 'version_installed'
2019-06-20 10:35:00 DEBUG (MainThread) [custom_components.hacs.frontend] GET API call for log with get
2019-06-20 10:35:40 ERROR (MainThread) [custom_components.hacs.frontend] 'NoneType' object has no attribute 'version_installed'
2019-06-20 10:35:41 DEBUG (MainThread) [custom_components.hacs.frontend] GET API call for log with get
2019-06-20 10:36:00 ERROR (MainThread) [custom_components.hacs.frontend] 'NoneType' object has no attribute 'version_installed'
2019-06-20 10:36:09 DEBUG (MainThread) [custom_components.hacs.frontend] GET API call for log with get
2019-06-20 10:36:09 ERROR (MainThread) [custom_components.hacs.frontend] 'NoneType' object has no attribute 'version_installed'
2019-06-20 10:36:10 DEBUG (MainThread) [custom_components.hacs.frontend] GET API call for log with get
2019-06-20 10:37:42 ERROR (MainThread) [custom_components.hacs.frontend] 'NoneType' object has no attribute 'version_installed'
2019-06-20 10:37:44 DEBUG (MainThread) [custom_components.hacs.frontend] GET API call for log with get
2019-06-20 10:37:50 DEBUG (MainThread) [custom_components.hacs.frontend] Tried to serve up '/config/www/community/atomic_calendar/atomic_calendar.js' but it does not exist
2019-06-20 10:37:50 DEBUG (MainThread) [custom_components.hacs.frontend] there was an issue trying to serve atomic_calendar/atomic_calendar.js - Not Found
2019-06-20 10:38:08 ERROR (MainThread) [custom_components.hacs.frontend] 'NoneType' object has no attribute 'version_installed'
2019-06-20 10:38:12 DEBUG (MainThread) [custom_components.hacs.frontend] GET API call for log with get
```

**Comment by ludeeus** [comment]
please paste your entire startup log from home assistant (using hastebin)

**Comment by CiquattroFPV** [comment]
```
2019-06-20 10:52:02 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-06-20 10:52:02 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-06-20 10:52:05 INFO (MainThread) [custom_components.hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)
Version: 0.9.0
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/hacs/issues
-------------------------------------------------------------------

2019-06-20 10:52:36 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 357, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: calendar.contacts
2019-06-20 10:52:49 ERROR (SyncWorker_2) [homeassistant.components.ios.notify] The notify.ios platform was loaded but no devices exist! Please check the documentation at https://home-assistant.io/ecosystem/ios/notifications/ for more information
2019-06-20 10:52:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1127, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service group/set
2019-06-20 10:52:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1127, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service group/set
2019-06-20 10:52:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1127, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service group/set
2019-06-20 10:52:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1127, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service group/set
2019-06-20 10:52:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1127, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service group/set
2019-06-20 10:52:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1127, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service group/set
2019-06-20 10:52:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1127, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service group/set
2019-06-20 10:52:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1127, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service group/set
2019-06-20 10:52:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1127, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service group/set
2019-06-20 10:52:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1127, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service group/set
2019-06-20 10:52:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1127, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service group/set
2019-06-20 10:53:02 INFO (MainThread) [custom_components.hacs.hacs] Runing startup tasks.
2019-06-20 10:53:18 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /discovery request
2019-06-20 10:53:18 ERROR (SyncWorker_5) [homeassistant.components.cert_expiry.sensor] Cannot connect to nico-casetta.dyndns.org
2019-06-20 10:53:18 ERROR (MainThread) [homeassistant.components.hassio.discovery] Can't read discover info: 
2019-06-20 10:53:22 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/aiogithub.py", line 53, in get_repo
    response = await self.session.get(url, headers=headers)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase.py", line 57, in startup_tasks
    repository = await self.aiogithub.get_repo("custom-components/hacs")
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/config/custom_components/hacs/aiogithub.py", line 61, in get_repo
    raise AIOGitHubException(response["message"])
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
2019-06-20 10:53:56 ERROR (MainThread) [frontend.js.latest.201906040] https://nico-casetta.dyndns.org:8123/config/core:0:0 Uncaught 
2019-06-20 10:53:56 ERROR (MainThread) [frontend.js.latest.201906040] https://nico-casetta.dyndns.org:8123/community:0:0 Uncaught 
2019-06-20 10:54:47 ERROR (MainThread) [custom_components.hacs.frontend] 'NoneType' object has no attribute 'version_installed'

```

**Comment by ludeeus** [comment]
You have a lot of errors in your setup.
Please disable HACS untill you correct all of them.
Then pull the latest master branch (I just updated it)

**Comment by CiquattroFPV** [comment]
I don't think it's a problem related to other errors by the way I saw on the github personal token page that the token is in the status of "Never used"

**Comment by ludeeus** [comment]
It never gets that far (probably due to network issues)
Your cert sensor for instance (network) are also failing.

**Comment by CiquattroFPV** [comment]
I have done a physical restart of the raspberry and after this it worked.
