### ISSUE TITLE
Community Page stay in Background task running, refresh the page in a little while

### ISSUE THREAD

**Issue by Chiunownow** [custom-components/hacs#170]
## Version of HACS
0.9.0

## Describe the bug
Community Page stay in Background task running, refresh the page in a little while

## Debug log
Error doing job: Task exception was never retrieved
上午2:15 custom_components/hacs/aiogithub.py (ERROR)

### Log Details (ERROR)
Wed Jun 26 2019 02:15:41 GMT+0800 (中国标准时间)

````
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/chiunownow/.homeassistant/custom_components/hacs/aiogithub.py", line 56, in get_repo
    response = await self.session.get(url, headers=headers)
  File "/home/chiunownow/hass/lib/python3.6/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/home/chiunownow/hass/lib/python3.6/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/chiunownow/hass/lib/python3.6/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/home/chiunownow/hass/lib/python3.6/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/home/chiunownow/hass/lib/python3.6/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 781, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chiunownow/.homeassistant/custom_components/hacs/hacsbase.py", line 57, in startup_tasks
    repository = await self.aiogithub.get_repo("custom-components/hacs")
  File "/home/chiunownow/hass/lib/python3.6/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/home/chiunownow/.homeassistant/custom_components/hacs/aiogithub.py", line 64, in get_repo
    raise AIOGitHubException(response["message"])
  File "/home/chiunownow/hass/lib/python3.6/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/home/chiunownow/hass/lib/python3.6/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
````

**Comment by ludeeus** [comment]
Reboot the server
