### ISSUE TITLE
HACS does not run properly

### ISSUE THREAD

**Issue by jojoro1** [custom-components/hacs#204]
## Version of HACS
0.10.0

## Describe the bug
HACS background task not finishing. In UI message "Background task running, refresh the page in a little while." is showing permanent. After restarting hassio all installed integrations/plugins dissapearing from "Overview" tab. 

.storage/hacs file has only "false" word inside

## Debug log

```text

----------------------------------------------------------------
HACS (Home Assistant Community Store)
Version: DEV
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/hacs/issues
-------------------------------------------------------------------

2019-06-30 17:37:16 ERROR (MainThread) [custom_components.hacs] You are running a DEV version of HACS, this is not intended for regular use.
2019-06-30 17:37:29 INFO (MainThread) [custom_components.hacs.hacs] Runing startup tasks.
2019-06-30 17:37:29 INFO (MainThread) [custom_components.hacs.hacs] Trying to load existing data.
2019-06-30 17:37:29 DEBUG (MainThread) [custom_components.hacs.storage] Reading from datastore /config/.storage/hacs.
2019-06-30 17:37:30 DEBUG (MainThread) [custom_components.hacs.hacs] Skipping repositories in blacklist []
2019-06-30 17:37:30 INFO (MainThread) [custom_components.hacs.hacs] Fetching updated blacklist
2019-06-30 17:37:32 INFO (MainThread) [custom_components.hacs.hacs] Fetching updated integration repository list
2019-06-30 17:37:33 DEBUG (MainThread) [custom_components.hacs.frontend] Serving banner-card/banner-card.js from /config/www/community/banner-card/banner-card.js.gz
2019-06-30 17:37:33 DEBUG (MainThread) [custom_components.hacs.frontend] Serving dual-gauge-card/dual-gauge-card.js from /config/www/community/dual-gauge-card/dual-gauge-card.js.gz
2019-06-30 17:37:33 DEBUG (MainThread) [custom_components.hacs.frontend] Serving secondaryinfo-entity-row/secondaryinfo-entity-row.js from /config/www/community/secondaryinfo-entity-row/secondaryinfo-entity-row.js.gz
2019-06-30 17:37:33 DEBUG (MainThread) [custom_components.hacs.frontend] Serving button-card/button-card.js from /config/www/community/button-card/button-card.js.gz
2019-06-30 17:37:39 INFO (MainThread) [custom_components.hacs.hacs] Fetching updated plugin repository list
2019-06-30 17:37:46 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.brewdog
2019-06-30 17:37:48 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/switch.hadockermon
2019-06-30 17:37:51 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/hassbian_config
2019-06-30 17:37:53 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.weatheralerts
2019-06-30 17:37:55 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.wienerlinien
2019-06-30 17:37:56 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/binary_sensor.hadockermon
2019-06-30 17:37:58 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.rpi_power
2019-06-30 17:38:01 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.untappd
2019-06-30 17:38:03 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/authenticated
2019-06-30 17:38:06 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sickchill
2019-06-30 17:38:08 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/usps_mail
2019-06-30 17:38:10 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/camera.unsplash
2019-06-30 17:38:12 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/camera.combined
2019-06-30 17:38:13 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.custom_aftership
2019-06-30 17:38:15 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/feedparser
2019-06-30 17:38:17 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/camera.multisource
2019-06-30 17:38:19 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.personalcapital
2019-06-30 17:38:22 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.trakt
2019-06-30 17:38:24 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/climate.e_thermostaat
2019-06-30 17:38:26 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.geoip
2019-06-30 17:38:28 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/media_player.braviatv_psk
2019-06-30 17:38:30 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.sonarr_upcoming_media
2019-06-30 17:38:32 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.radarr_upcoming_media
2019-06-30 17:38:35 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.owlintuition
2019-06-30 17:38:37 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.unifigateway
2019-06-30 17:38:39 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.ssh
2019-06-30 17:38:42 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.plex_recently_added
2019-06-30 17:38:44 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.ctabustracker
2019-06-30 17:38:46 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.kodi_recently_added
2019-06-30 17:38:48 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/youtube
2019-06-30 17:38:51 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/hacs
2019-06-30 17:38:54 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/config_check
2019-06-30 17:38:57 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.yandex_maps
2019-06-30 17:38:59 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/climate.programmable_thermostat
2019-06-30 17:39:01 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.file_restore
2019-06-30 17:39:04 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/complimentr
2019-06-30 17:39:06 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.avanza_stock
2019-06-30 17:39:08 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/gpodder
2019-06-30 17:39:10 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/sensor.airthings_wave
2019-06-30 17:39:12 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/breaking_changes
2019-06-30 17:39:14 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/grocy
2019-06-30 17:39:16 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/qbo
2019-06-30 17:39:18 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-components/google_keep
2019-06-30 17:39:19 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for StyraHem/ShellyForHASS
2019-06-30 17:39:21 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for isabellaalstrom/sensor.krisinformation
2019-06-30 17:39:24 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for JurajNyiri/HomeAssistant-Tavos
2019-06-30 17:39:27 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for JurajNyiri/HomeAssistant-Atrea
2019-06-30 17:39:29 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for TimSoethout/goodwe-sems-home-assistant
2019-06-30 17:39:32 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for bramkragten/lyric
2019-06-30 17:39:34 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for bramkragten/mind
2019-06-30 17:39:37 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for bouwew/sems2mqtt
2019-06-30 17:39:39 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for akasma74/Hass-Custom-Alarm
2019-06-30 17:39:41 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for keatontaylor/alexa_media_player
2019-06-30 17:39:43 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for albertogeniola/meross-homeassistant
2019-06-30 17:39:46 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for mudape/iphonedetect
2019-06-30 17:39:48 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for bertbert72/HomeAssistant_VirginTivo
2019-06-30 17:39:51 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for nstrelow/ha_philips_android_tv
2019-06-30 17:39:53 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for rsnodgrass/hass-integrations
2019-06-30 17:39:55 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for Ceerbeerus/beerbolaget
2019-06-30 17:39:57 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for thomasloven/hass-browser_mod
2019-06-30 17:40:00 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for claytonjn/hass-circadian_lighting
2019-06-30 17:40:02 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for xMrVizzy/Philips-AirPurifier
2019-06-30 17:40:05 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for jomwells/ambilights
2019-06-30 17:40:07 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for jomwells/ambihue
2019-06-30 17:40:09 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for jomwells/ambilight-yeelight
2019-06-30 17:40:12 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/text-element
2019-06-30 17:40:14 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/circle-sensor-card
2019-06-30 17:40:17 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/state-attribute-element
2019-06-30 17:40:20 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/vertical-stack-in-card
2019-06-30 17:40:23 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/state-element
2019-06-30 17:40:25 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/canvas-gauge-card
2019-06-30 17:40:28 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/dual-gauge-card
2019-06-30 17:40:31 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/beer-card
2019-06-30 17:40:33 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/ext-weblink
2019-06-30 17:40:36 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/aftership-card
2019-06-30 17:40:38 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/username-element
2019-06-30 17:40:41 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/list-card
2019-06-30 17:40:43 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/button-card
2019-06-30 17:40:46 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/rmv-card
2019-06-30 17:40:48 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/upcoming-media-card
2019-06-30 17:40:51 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/surveillance-card
2019-06-30 17:40:54 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/light-entity-row
2019-06-30 17:40:57 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/button-entity-row
2019-06-30 17:40:59 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/flex-table-card
2019-06-30 17:41:02 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/secondaryinfo-entity-row
2019-06-30 17:41:05 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/bar-card
2019-06-30 17:41:07 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/roku-card
2019-06-30 17:41:10 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/pc-card
2019-06-30 17:41:13 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/config-template-card
2019-06-30 17:41:16 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/spotify-card
2019-06-30 17:41:18 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/podcast-card
2019-06-30 17:41:21 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/untappd-card
2019-06-30 17:41:23 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/group-element
2019-06-30 17:41:26 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/text-divider-row
2019-06-30 17:41:29 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/cover-element
2019-06-30 17:41:32 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/radial-menu
2019-06-30 17:41:34 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/playback-card
2019-06-30 17:41:37 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/text-action-element
2019-06-30 17:41:39 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/bignumber-card
2019-06-30 17:41:42 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/entity-attributes-card
2019-06-30 17:41:45 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/gauge-card
2019-06-30 17:41:47 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/group-card
2019-06-30 17:41:50 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/home-setter
2019-06-30 17:41:52 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/monster-card
2019-06-30 17:41:55 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/plan-coordinates
2019-06-30 17:41:58 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/muuri-grid
2019-06-30 17:42:00 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for custom-cards/decluttering-card
2019-06-30 17:42:03 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for maykar/compact-custom-header
2019-06-30 17:42:06 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for maykar/lovelace-swipe-navigation
2019-06-30 17:42:09 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for peternijssen/lovelace-postnl-card
2019-06-30 17:42:13 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for nervetattoo/simple-thermostat
2019-06-30 17:42:15 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for nervetattoo/banner-card
2019-06-30 17:42:18 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for kalkih/mini-media-player
2019-06-30 17:42:20 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for kalkih/mini-graph-card
2019-06-30 17:42:23 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for finity69x2/fan-control-entity-row
2019-06-30 17:42:25 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for thomasloven/lovelace-card-mod
2019-06-30 17:42:28 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for thomasloven/lovelace-markdown-mod
2019-06-30 17:42:31 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for thomasloven/lovelace-slider-entity-row
2019-06-30 17:42:33 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for thomasloven/lovelace-fold-entity-row
2019-06-30 17:42:36 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for isabellaalstrom/krisinfo-card
2019-06-30 17:42:38 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for tcarlsen/lovelace-light-with-profiles
2019-06-30 17:42:41 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for atomic7777/atomic_calendar
2019-06-30 17:42:44 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for bramkragten/weather-card
2019-06-30 17:42:46 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for bramkragten/swipe-card
2019-06-30 17:42:49 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for CyrisXD/love-lock-card
2019-06-30 17:42:52 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for dimagoltsman/content-card-remote-control
2019-06-30 17:42:55 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for ljmerza/calendar-card
2019-06-30 17:42:57 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for ljmerza/light-entity-card
2019-06-30 17:43:00 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for ljmerza/fitbit-card
2019-06-30 17:43:04 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for ljmerza/github-card
2019-06-30 17:43:07 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for ljmerza/waze-card
2019-06-30 17:43:09 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for ljmerza/reddit-card
2019-06-30 17:43:11 INFO (MainThread) [custom_components.hacs.hacs] Starting repository registration for ljmerza/tracking-number-card
2019-06-30 17:43:14 INFO (MainThread) [custom_components.hacs.storage] Saving data
2019-06-30 17:43:14 INFO (MainThread) [custom_components.hacs.migration] Flushing data to storage.
2019-06-30 17:43:16 DEBUG (MainThread) [custom_components.hacs.storage] Reading from datastore /config/.storage/hacs.
2019-06-30 17:43:16 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase.py", line 70, in startup_tasks
    old_hacs = old.get("repositories", {}).get(repository.repository_id, {})
AttributeError: 'bool' object has no attribute 'get'

```

**Comment by lubbertkramer** [comment]
Here the same problem, have multiple installed but not showing up in the store after a reboot/refresh. I see only two HACS files under storage:

![image](https://user-images.githubusercontent.com/8224586/60400337-b95d7e80-9b72-11e9-89ec-ff3a7f147714.png)

![image](https://user-images.githubusercontent.com/8224586/60400345-deea8800-9b72-11e9-8f68-8a736f6fd9e7.png)

Running Home Assistant: 95.4 installed in docker on a NUC with Ubuntu with version of HACS

**Comment by ludeeus** [comment]
Have a look here <https://custom-components.github.io/hacs/faq/#known-limitations>

**Comment by lubbertkramer** [comment]
> Have a look here https://custom-components.github.io/hacs/faq/#known-limitations

Thanks, that i didn't saw indeed. Is there a way to fix it or do i need to install all again and then keep in mind the limitations?

**Comment by ludeeus** [comment]
"install" all again, but that only re-downloads, so no big deal :)

**Comment by lubbertkramer** [comment]
Thanks will do and i will try to keep in mind that i don't need to restart while scanning:)

**Comment by ludeeus** [comment]
Should be fixed in 0.11.0 <https://github.com/custom-components/hacs/releases/tag/0.11.0>

**Comment by markgaze** [comment]
Can confirm that it's fixed for me, thanks for fixing so soon @ludeeus. Loving HACS so far! :slightly_smiling_face:

**Comment by jojoro1** [comment]
Now it's fine. Thank You.

**Comment by kurteknikk** [comment]
I had the same issue and now its fixed, thanks

**Comment by evgenblum** [comment]
I have the same problem. Can't upgrade HACS because always background tasks are running. Please, advice.
Here are my logs:

Action is disabled while background tasks is running.

Logger: homeassistant.core
Source: custom_components/hacs/repositories/appdaemon.py:48
First occurred: 10:34:13 PM (1 occurrences)
Last logged: 10:34:13 PM
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 197, in startup_tasks
    await self.load_known_repositories()
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 386, in load_known_repositories
    await self.factory.execute()
  File "/config/custom_components/hacs/hacsbase/task_factory.py", line 30, in execute
    await asyncio.gather(*self.tasks)
  File "/config/custom_components/hacs/hacsbase/task_factory.py", line 66, in safe_register
    await hacs.register_repository(repo, category)
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 157, in register_repository
    await repository.registration()
  File "/config/custom_components/hacs/repositories/appdaemon.py", line 60, in registration
    if not await self.validate_repository():
  File "/config/custom_components/hacs/repositories/appdaemon.py", line 48, in validate_repository
    for filename in self.content.objects:
TypeError: 'AIOGithubRepositoryContent' object is not iterable
