### ISSUE TITLE
KeyError: 'appdaemon' (When accessing the store)

### ISSUE THREAD

**Issue by brinzlee** [custom-components/hacs#218]
Installed HACS on HassIO version 0.95.4

-->

## Version of HACS
0.11.1

## Describe the bug
When I click on store all I get is

500 Internal Server Error
Server got itself in trouble

## Debug log
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 67, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 216, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 115, in handle
    result = await result
  File "/config/custom_components/hacs/frontend/views/store.py", line 75, in get
    types[repository.repository_type].append(card)
KeyError: 'appdaemon'
```

**Comment by ludeeus** [comment]
Is this a new install, or did you upgrade from a previous version?
Have you added `appdaemon: true` to your config?
Are you using `appdaemon` ?

**Comment by ludeeus** [comment]
Got the same issue after removing `appdaemon: True` from my config.
Will be fixed in the next version, for now just add back `appdaemon: True` to your config.

**Comment by brinzlee** [comment]
It was a new install....I did add appdaemon: true then took it out as you did. Have reinstated it and all is good again. 
Thanks for the quick reply

**Comment by dpembo** [comment]
I had similar issue - noticed I had 3 random custom repositories that were listed that I'm pretty sure I didn't add when I removed them the issue went away.

**Comment by Xilt** [comment]
Once trying to install custom repository I am getting the same error all the time, this time with different reason as spotted in the log. 

`Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/ban.py", line 67, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/auth.py", line 216, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/view.py", line 115, in handle
    result = await result
  File "/home/homeassistant/.homeassistant/custom_components/hacs/frontend/views/api.py", line 182, in post
    repository_name = repository_name.split()[0]
IndexError: list index out of range`

**Comment by Xilt** [comment]
Once trying to install custom repository I am getting the same error all the time, this time with different reason as spotted in the log.

`Traceback (most recent call last):

 File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/ban.py", line 67, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/auth.py", line 216, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/view.py", line 115, in handle
    result = await result
  File "/home/homeassistant/.homeassistant/custom_components/hacs/frontend/views/api.py", line 182, in post
    repository_name = repository_name.split()[0]
IndexError: list index out of range`

**Comment by ludeeus** [comment]
@Xilt open a seperate issue, and fill out the issue template.

**Comment by ludeeus** [comment]
Corrected in https://github.com/custom-components/hacs/releases/tag/0.12.0
