### ISSUE TITLE
Just Stop Working 

### ISSUE THREAD

**Issue by MYLE-01** [custom-components/hacs#261]
Sorry about bad Heading  

was playing with some automation NOTHING to do with this

Here the log
```
2019-07-12 16:19:23 ERROR (MainThread) [homeassistant.setup] Error during setup of component hacs
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "uvloop/loop.pyx", line 1464, in getaddrinfo
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/hacs/__init__.py", line 89, in async_setup
    await configure_hacs(hass, github_token, config_dir)
  File "/config/custom_components/hacs/__init__.py", line 159, in configure_hacs
    hacs.hacs_github = await hacs.aiogithub.get_repo("custom-components/hacs")
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/config/custom_components/hacs/aiogithub.py", line 56, in get_repo
    response = await self.session.get(url, headers=headers)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.github.com:443 ssl:None [Try again]
2019-07-12 16:19:23 ERROR (MainThread) [homeassistant.helpers.entity] Update for binary_sensor.car_wash fails
```
Hope its not ME

even did a reboot

**Comment by ludeeus** [comment]
You have network issues, it cannot contact Github.
```
Cannot connect to host api.github.com:443 ssl:None [Try again]
```

**Comment by MYLE-01** [comment]
How did miss that Thanks

**Comment by MYLE-01** [comment]
Thanks @ludeeus

all Fix Router was the problem
