### ISSUE TITLE
Intergration not found hacs

### ISSUE THREAD

**Issue by eterpstra** [custom-components/hacs#262]
Hello,

I am currently on a fresh installation of HASS.IO on docker. the path in docker for hassio is /user/share/hassio/homeassistant/

I created the folder custom_components and downloaded the git files / hacs files. 
hacs is placed into /custom_components. 
In the configration.yaml i placed the this:

```
hacs: 
   token: 4878f7a6265xxxxxxxxxxxxxxxxxxxxxxxxxf9a4
```
However, HA will not restart due this error:

Integration not found: hacs

What am i doing wrong? I

**Comment by ludeeus** [comment]
Restart HA one time _before_ adding it to config.

**Comment by Chimestrike** [comment]
I had a fully working install of HACS till about a week ago, I had to restart my machine and when it came back up I no longer have the ingress menu and I receive the  "Invalid config" message in HA, I've reinstalled HACS from fresh and also had 2 HA upgrades this week and still no luck.

Also a few of our guys in our group have had similar issues, but the error shows as below so this could be further issue and not just a single install error:

Fri Jul 26 2019 11:06:37 GMT+0100 (British Summer Time)
Error during setup of component hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/hacs/__init__.py", line 69, in async_setup
    await configure_hacs(hass, config[DOMAIN], config_dir)
  File "/config/custom_components/hacs/__init__.py", line 171, in configure_hacs
    hacs.store.restore_values()
  File "/config/custom_components/hacs/hacsbase/data.py", line 102, in restore_values
    store = self.read()
  File "/config/custom_components/hacs/hacsbase/data.py", line 41, in read
    content = json.loads(content)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 3426 column 13 (char 122870)

**Comment by gmkfak** [comment]
Hi,
I had the same problem.
I removed hacs: 
   token: 4878f7a6265xxxxxxxxxxxxxxxxxxxxxxxxxf9a4
and rebooted and found hacs in integrations section.
