### ISSUE TITLE
hacs disappear from side panel

### ISSUE THREAD

**Issue by Dmxsir** [custom-components/hacs#268]
<!-- Before you open a new issue, search through the existing issues to see if others have had the same problem.

## Version of HACS
```HACS (Home Assistant Community Store)
Version: 0.11.1
This is a custom integration```
<!-- If you are not using the newest version, download and try that before opening an issue
If you are unsure about the version check the "SETTINGS" tab.
-->


## Describe the bug
I installed and set everything right, and it worked for a while.
and now its disappear from side panel and give me error in the log.


## Debug log

```
2019-07-13 16:02:57 INFO (MainThread) [homeassistant.setup] Setting up hacs
2019-07-13 16:02:57 INFO (MainThread) [custom_components.hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)
Version: 0.11.1
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/hacs/issues
-------------------------------------------------------------------

2019-07-13 16:03:05 ERROR (MainThread) [homeassistant.setup] Error during setup of component hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/hacs/__init__.py", line 89, in async_setup
    await configure_hacs(hass, github_token, config_dir)
  File "/config/custom_components/hacs/__init__.py", line 164, in configure_hacs
    hacs.store.restore_values()
  File "/config/custom_components/hacs/hacsdatastore.py", line 93, in restore_values
    store = self.read()
  File "/config/custom_components/hacs/hacsdatastore.py", line 32, in read
    content = json.loads(content)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by ludeeus** [comment]
From those logs it looks like you removed the content of `.storage/hacs` or changed the permissions of that file.

**Comment by Dmxsir** [comment]
this one?
![hacs](https://user-images.githubusercontent.com/36658595/61174495-963ac200-a5a9-11e9-9f6d-bc0fa8d17400.JPG)

**Comment by Dmxsir** [comment]
i did restart my RPI a few times , but it didn't help.

**Comment by ludeeus** [comment]
If you look at it, it has 0KB, something has happened to it.
Delete that file, then restart HA and it will start working again.

**Comment by Dmxsir** [comment]
thank you !!!
its working again !
