### ISSUE TITLE
IndexError: list index out of range (When adding custom repository)

### ISSUE THREAD

**Issue by Xilt** [custom-components/hacs#273]
Installed HACS on Python venv 0.95.4 RPi3B+

## Version of HACS

0.11.1
## Describe the bug
Everytime I am trying to add custom repository I receive the error with the following reason.

## Debug log

```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/ban.py", line 67, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/auth.py", line 216, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/view.py", line 115, in handle
    result = await result
  File "/home/homeassistant/.homeassistant/custom_components/hacs/frontend/views/api.py", line 182, in post
    repository_name = repository_name.split()[0]
IndexError: list index out of range

```

**Comment by ludeeus** [comment]
Which repository?

**Comment by Xilt** [comment]
All good. I had it all wrong. Its working as it should.  I was trying to load custom plugin without firs filling out the http path to custom repository. I was under the impression that new window would popup with request to fill additional info. Forgive me for raising false alarm. Please disregard/delete my post entirely. Thank you.
