### ISSUE TITLE
Something is wrong... Error code: I know kung fu.

### ISSUE THREAD

**Issue by erpuma63** [custom-components/hacs#276]
## Debug log

```text

Add your logs here.

```

**Comment by ian-tait** [comment]
I get the following error in HA.
When looking at the Overview I get a flowchart.

`Sun Jul 14 2019 20:42:15 GMT+0100 (British Summer Time)
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 67, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 216, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 115, in handle
    result = await result
  File "/config/custom_components/hacs/frontend/views/store.py", line 42, in get
    repository = RepositoryInformation(self.store.repositories[repository.repository_id])
KeyError: '194941760'`

**Comment by oli-f** [comment]
See https://github.com/custom-components/hacs/releases

> NB!: If you upgrade to this version with HACS, it will break the UI, to resolve that simply restart Home Assistant.
> 
> When you click "UPDATE" you will see this (and again, this is expected)
> 
> 500 Internal Server Error
> Server got itself in trouble

**Comment by ian-tait** [comment]
Ok, That solved it. 
Sorry I didn't read that first time round.

**Comment by erpuma63** [comment]
solved thanks , same i didn't read as well
