### ISSUE TITLE
Error during setup of component hacs

### ISSUE THREAD

**Issue by ian-tait** [custom-components/hacs#278]
Community has disappeared from the left menu.
Tried to reinstall with the latest version nothing is working.

```
Mon Jul 15 2019 00:00:17 GMT+0100 (British Summer Time)
Error during setup of component hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/hacs/__init__.py", line 69, in async_setup
    await configure_hacs(hass, config[DOMAIN], config_dir)
  File "/config/custom_components/hacs/__init__.py", line 171, in configure_hacs
    hacs.store.restore_values()
  File "/config/custom_components/hacs/hacsbase/data.py", line 102, in restore_values
    store = self.read()
  File "/config/custom_components/hacs/hacsbase/data.py", line 41, in read
    content = json.loads(content)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1713 column 39 (char 61440)Mon Jul 15 2019 00:00:17 GMT+0100 (British Summer Time)
Error during setup of component hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/hacs/__init__.py", line 69, in async_setup
    await configure_hacs(hass, config[DOMAIN], config_dir)
  File "/config/custom_components/hacs/__init__.py", line 171, in configure_hacs
    hacs.store.restore_values()
  File "/config/custom_components/hacs/hacsbase/data.py", line 102, in restore_values
    store = self.read()
  File "/config/custom_components/hacs/hacsbase/data.py", line 41, in read
    content = json.loads(content)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1713 column 39 (char 61440)
```

**Comment by ludeeus** [comment]
What is on line 1713 in `.storage/hacs` ?

**Comment by ian-tait** [comment]
The doc looks to e not complete.
It stops on line 1712 

`"187245528": {                
            "custom": false,    
            "description": null,
            "hide": false,
            "installed_commit": null,
            "installed": false,                                   
            "last_commit": null,
            "name": "home-setter",   
            "new": true,       
            "repository_name": "custom-cards/home-setter",
            "repository_type": "plugin",
            "show_beta": false,
            "topics": [],                            
            "track": true,                 
            "last_release_tag": "0.0.2",
            "version_installed": null,
~                                `

Not sure why it would do this?
Where does this file come from? I assume its part of the install?

**Comment by ludeeus** [comment]
I have never seen that happen to _any_ file, HACS needs that file.
Try deleting it, then restart HA.

**Comment by schneekluth** [comment]
Lately my Raspberry Pi ran out of space and was no longer available on my network. After freeing some space this error came up and HACS was not able to be loaded.
