### ISSUE TITLE
Doesn't work offline

### ISSUE THREAD

**Issue by Destix** [custom-components/hacs#334]
Home Assistant
0.96.3

HACS
Version: 0.12.1 

Seems like HACS component does not load without internet.
And as long as configuration uses not /local/ links, all custom cards and integrations are not loaded.
```
- url: /community_plugin/banner-card/banner-card.js
  type: module
```

However plugins configured using /local/community/ works fine.
```
  - url: /local/community/banner-card/banner-card.js
    type: module
```

Logs:

```
Error during setup of component hacs
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "uvloop/loop.pyx", line 1464, in getaddrinfo
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/hacs/__init__.py", line 69, in async_setup
    await configure_hacs(hass, config[DOMAIN], config_dir)
  File "/config/custom_components/hacs/__init__.py", line 164, in configure_hacs
    hacs.hacs_github = await hacs.aiogithub.get_repo("custom-components/hacs")
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/config/custom_components/hacs/aiogithub/aiogithub.py", line 45, in get_repo
    response = await self.session.get(url, headers=headers)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.github.com:443 ssl:None [Try again]
```

**Comment by ludeeus** [comment]
It is not designed to work without internet, updating and downloading from github is it's main functionality.

**Comment by jurenovic** [comment]
@Destix I had a really bad experience this night with your plugin. My ISP had a major outage this night and by the morning the thing still hasn't been fixed so the entire HomeAssistant on docker was not responding due too many errors like the one up. 
In my opinion none of the plugins should be designed to work only with internet. If someone wants to keep home assistant offline for privacy or whatever other reason they should be able to. In case of HACS I think caching and fallback retry would be great addition to great benefit that it provides. 

Would you reconsider the design decisions? Thanks for your great work.
