### ISSUE TITLE
HACS not loading 

### ISSUE THREAD

**Issue by Chimestrike** [custom-components/hacs#339]
I had a fully working install of HACS till about a week ago, I had to restart my machine and when it came back up I no longer have the ingress menu and I receive the "Invalid config" message in HA, I've reinstalled HACS from fresh and also had multiple HA upgrades this week and still no luck.

Also a few of our guys in our group have had similar issues, but the error shows as below so this could be further issue and not just a single install error:

This is with HA 0.95 then 0.96 with multiple patches this week (.1 to .5) and HACS 12.1 (previous version was 12 I believe)

Fri Jul 26 2019 11:06:37 GMT+0100 (British Summer Time)
Error during setup of component hacs
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 153, in _async_setup_component
hass, processed_config)
File "/config/custom_components/hacs/init.py", line 69, in async_setup
await configure_hacs(hass, config[DOMAIN], config_dir)
File "/config/custom_components/hacs/init.py", line 171, in configure_hacs
hacs.store.restore_values()
File "/config/custom_components/hacs/hacsbase/data.py", line 102, in restore_values
store = self.read()
File "/config/custom_components/hacs/hacsbase/data.py", line 41, in read
content = json.loads(content)
File "/usr/local/lib/python3.7/json/init.py", line 348, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 3426 column 13 (char 122870)

So far I've tried:

Reinstall HACS
Recreate API in Github
Updated HA

**Comment by ludeeus** [comment]
The `.storage/hacs` file have corrupted, you need to delete that and restart HA after that, after deletion you will need to "install" all installed elements to re-register them.

**Comment by Chimestrike** [comment]
That's fixed it, thank you for the assistance.

**Comment by corvy** [comment]
This also solved my issue. Thanks! :)
