### ISSUE TITLE
Improve theme support (background image)

### ISSUE THREAD

**Issue by capstan1** [custom-components/hacs#346]
**Is your feature request related to a problem? Please describe.**
Some themes provide a background image to be used together with the theme. Background images are usually placed in /www folder and referenced from theme-name.yaml
Currently the picture is not downloaded to the install.

**Describe the solution you'd like**
If a picture is provided in the repo inside an /www folder, the picture should be downloaded.

**Comment by ludeeus** [comment]
This will require a major rewrite of the core install/remove functions as well the theme handling.
Do you have examples of repositories with that structure?

**Comment by capstan1** [comment]
Hi,
[my repo](https://github.com/capstan1/summer-breeze) has a structure like this.

I can understand if that's not the direction you want to take, it's just an idea I had to better support themes.

**Comment by ludeeus** [comment]
I will not be adding this if a developer wants to ship an image with the theme that can be done with base64 https://css-tricks.com/data-uris/

**Comment by naofireblade** [comment]
@ludeeus I currently use your recommended solution but this triggers errors in the home assistant on every start and theme change. Home assistant stores every theme change in the database and the theme data is now to long for the mysql field:

```
2019-11-26 20:06:28 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'event_data' at row 1")
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s)]
[parameters: ('themes_updated', '{"themes": {"clear-dark": {"lovelace-background": "center / cover no-repeat url(data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/4QBmRXhpZgAATU0AKg ... (250725 characters truncated) ... or)", "hacs-status-pending-restart": "var(--text-light-color)", "hacs-status-pending-update": "var(--accent-color)"}}, "default_theme": "clear-dark"}', 'LOCAL', datetime.datetime(2019, 11, 26, 19, 4, 28, 494370, tzinfo=<UTC>), datetime.datetime(2019, 11, 26, 19, 6, 28, 856964), '76a30ef593d940ebbab7f6dbc08867f5', None)]
(Background on this error at: http://sqlalche.me/e/9h9h)
2019-11-26 20:06:28 ERROR (Recorder) [homeassistant.components.recorder] Error saving event: <Event themes_updated[L]: themes=clear-dark=lovelace-background=center / cover no-repeat url(data:image/jpeg;HERE COMES THE BACKGROUND IMAGE) fixed, text-color=#636B75, text-medium-color=#8c96a5, text-light-color=#BAC0C6, accent-color=#00a1ff, background-color=#F7F8F9, background-color-2=#F4F5F6, background-card-color=rgba(255,255,255,1.0), border-color=#E8E8E8, primary-color=var(--text-color), text-primary-color=#FFF, paper-listbox-background-color=var(--background-color), paper-card-header-color=var(--text-color), primary-background-color=var(--background-color), paper-card-background-color=var(--background-card-color), dark-primary-color=var(--text-color), primary-text-color=var(--text-color), paper-listbox-color=var(--text-color), light-primary-color=var(--text-light-color), secondary-text-color=var(--text-medium-color), disabled-text-color=var(--text-light-color), paper-dialog-button-color=var(--text-color), secondary-background-color=var(--background-color-2), paper-item-icon-color=var(--text-light-color), paper-item-icon-active-color=var(--accent-color), switch-checked-color=var(--accent-color), switch-unchecked-button-color=#FFF, switch-unchecked-track-color=var(--disabled-text-color), paper-slider-active-color=var(--accent-color), paper-slider-container-color=#e5e7ea, paper-slider-knob-color=var(--text-light-color), paper-slider-knob-start-color=var(--text-light-color), ha-card-box-shadow=inset 0px 0px 0px 1px var(--border-color), hacs-badge-color=var(--accent-color), hacs-status-installed=var(--text-color), hacs-status-pending-restart=var(--text-light-color), hacs-status-pending-update=var(--accent-color), default_theme=clear-dark>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.DataError: (1406, "Data too long for column 'event_data' at row 1")
```
