### ISSUE TITLE
Unable to connect to Github

### ISSUE THREAD

**Issue by passie** [custom-components/hacs#351]
I migrated from a Raspberry Pi 3 to a Raspberry Pi 4 and restored a snap-shot.
After this hacs is unable to start properly.

In the Developer tool section i’m getting the following error message:

`Cannot connect to host api.github.com:443 ssl:None [Try again]` 

I reseted the github api key without luck.
I’m running the latest Home Assistant version 0.96.5

Full error message:

`2019-07-29 23:34:55 ERROR (MainThread) [homeassistant.setup] Error during setup of component hacs
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "uvloop/loop.pyx", line 1464, in getaddrinfo
socket.gaierror: [Errno -3] Try again
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/hacs/__init__.py", line 69, in async_setup
    await configure_hacs(hass, config[DOMAIN], config_dir)
  File "/config/custom_components/hacs/__init__.py", line 164, in configure_hacs
    hacs.hacs_github = await hacs.aiogithub.get_repo("custom-components/hacs")
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/config/custom_components/hacs/aiogithub/aiogithub.py", line 45, in get_repo
    response = await self.session.get(url, headers=headers)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.github.com:443 ssl:None [Try again]`

hacs config in configuration.yaml

`hacs:
  token: !secret github_access_token`

Any idea what’s wrong?

**Comment by ludeeus** [comment]
There is probably nothing wrong with your key.
Your Host have network issues and cant reach github.
This is out of the scope of this integration.
