### ISSUE TITLE
Total system crash

### ISSUE THREAD

**Issue by tomlut** [custom-components/hacs#354]
## Version of HACS

0.12.1 

## Describe the bug
I had a total system crash tonight. Not able to open the web front end and automations stopped. SSH was still working and I managed to download the logs before (successfully) restarting.

The log seems to suggest it all began with HACS. But I could be wrong and this could be a red herring. 

## Debug log

```text
2019-07-30 19:27:21 ERROR (MainThread) [pyhaversion] Timeouterror fetching version information from Hassio, 
2019-07-30 20:08:19 WARNING (MainThread) [custom_components.hacs.template] Error rendering info template 'value' is undefined
2019-07-30 20:09:35 WARNING (MainThread) [custom_components.hacs.template] Error rendering info template 'states' is undefined
2019-07-30 20:18:08 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 200, in update_repositories
    await repository.set_repository()
  File "/config/custom_components/hacs/repositories/hacsrepositorybase.py", line 413, in set_repository
    self.repository = await self.aiogithub.get_repo(self.repository_name)
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/config/custom_components/hacs/aiogithub/aiogithub.py", line 56, in get_repo
    raise AIOGitHubException(response["message"])
custom_components.hacs.aiogithub.exceptions.AIOGitHubException: Server Error
2019-07-30 20:18:08 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.lounge_av_rx fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 200, in update_repositories
    await repository.set_repository()
  File "/config/custom_components/hacs/repositories/hacsrepositorybase.py", line 413, in set_repository
    self.repository = await self.aiogithub.get_repo(self.repository_name)
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/config/custom_components/hacs/aiogithub/aiogithub.py", line 56, in get_repo
    raise AIOGitHubException(response["message"])
custom_components.hacs.aiogithub.exceptions.AIOGitHubException: Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in async_device_update
    await self.hass.async_add_executor_job(self.update)
concurrent.futures._base.CancelledError
2019-07-30 20:18:08 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.cinema_av_rx fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 200, in update_repositories
    await repository.set_repository()
  File "/config/custom_components/hacs/repositories/hacsrepositorybase.py", line 413, in set_repository
    self.repository = await self.aiogithub.get_repo(self.repository_name)
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/config/custom_components/hacs/aiogithub/aiogithub.py", line 56, in get_repo
    raise AIOGitHubException(response["message"])
custom_components.hacs.aiogithub.exceptions.AIOGitHubException: Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 366, in async_device_update
    await self.parallel_updates.acquire()
  File "/usr/local/lib/python3.7/asyncio/locks.py", line 474, in acquire
    await fut
concurrent.futures._base.CancelledError
2019-07-30 20:18:08 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.lounge_pc_kodi fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 200, in update_repositories
    await repository.set_repository()
  File "/config/custom_components/hacs/repositories/hacsrepositorybase.py", line 413, in set_repository
    self.repository = await self.aiogithub.get_repo(self.repository_name)
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/config/custom_components/hacs/aiogithub/aiogithub.py", line 56, in get_repo
    raise AIOGitHubException(response["message"])
custom_components.hacs.aiogithub.exceptions.AIOGitHubException: Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/components/kodi/media_player.py", line 450, in async_update
    self._players = await self._get_players()
  File "/usr/src/homeassistant/homeassistant/components/kodi/media_player.py", line 396, in _get_players
    return await self.server.Player.GetActivePlayers()
  File "/usr/local/lib/python3.7/site-packages/jsonrpc_async/jsonrpc.py", line 29, in send_message
    response = yield from self._request(data=message.serialize())
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "uvloop/loop.pyx", line 1894, in create_connection
  File "uvloop/loop.pyx", line 1883, in uvloop.loop.Loop.create_connection
concurrent.futures._base.CancelledError
2019-07-30 20:18:08 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.cinema_av_rx_zone_2 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 200, in update_repositories
    await repository.set_repository()
  File "/config/custom_components/hacs/repositories/hacsrepositorybase.py", line 413, in set_repository
    self.repository = await self.aiogithub.get_repo(self.repository_name)
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/config/custom_components/hacs/aiogithub/aiogithub.py", line 56, in get_repo
    raise AIOGitHubException(response["message"])
custom_components.hacs.aiogithub.exceptions.AIOGitHubException: Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 366, in async_device_update
    await self.parallel_updates.acquire()
  File "/usr/local/lib/python3.7/asyncio/locks.py", line 474, in acquire
    await fut
concurrent.futures._base.CancelledError
2019-07-30 20:18:08 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.lounge_av_rx_zone_2 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 200, in update_repositories
    await repository.set_repository()
  File "/config/custom_components/hacs/repositories/hacsrepositorybase.py", line 413, in set_repository
    self.repository = await self.aiogithub.get_repo(self.repository_name)
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/config/custom_components/hacs/aiogithub/aiogithub.py", line 56, in get_repo
    raise AIOGitHubException(response["message"])
custom_components.hacs.aiogithub.exceptions.AIOGitHubException: Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 366, in async_device_update
    await self.parallel_updates.acquire()
  File "/usr/local/lib/python3.7/asyncio/locks.py", line 474, in acquire
    await fut
concurrent.futures._base.CancelledError
2019-07-30 20:18:08 ERROR (SyncWorker_8) [concurrent.futures] exception calling callback for <Future at 0x7fb662df9750 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "uvloop/loop.pyx", line 1261, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 604, in uvloop.loop.Loop._call_soon
  File "uvloop/loop.pyx", line 608, in uvloop.loop.Loop._call_soon_handle
  File "uvloop/loop.pyx", line 637, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
2019-07-30 20:18:09 ERROR (SyncWorker_5) [concurrent.futures] exception calling callback for <Future at 0x7fb65faa0650 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "uvloop/loop.pyx", line 1261, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 604, in uvloop.loop.Loop._call_soon
  File "uvloop/loop.pyx", line 608, in uvloop.loop.Loop._call_soon_handle
  File "uvloop/loop.pyx", line 637, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
2019-07-30 20:18:09 ERROR (SyncWorker_2) [concurrent.futures] exception calling callback for <Future at 0x7fb6603f7290 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "uvloop/loop.pyx", line 1261, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 604, in uvloop.loop.Loop._call_soon
  File "uvloop/loop.pyx", line 608, in uvloop.loop.Loop._call_soon_handle
  File "uvloop/loop.pyx", line 637, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
2019-07-30 20:18:09 ERROR (SyncWorker_3) [concurrent.futures] exception calling callback for <Future at 0x7fb65fc339d0 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "uvloop/loop.pyx", line 1261, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 604, in uvloop.loop.Loop._call_soon
  File "uvloop/loop.pyx", line 608, in uvloop.loop.Loop._call_soon_handle
  File "uvloop/loop.pyx", line 637, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
2019-07-30 20:18:09 ERROR (SyncWorker_9) [concurrent.futures] exception calling callback for <Future at 0x7fb6603f7690 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "uvloop/loop.pyx", line 1261, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 604, in uvloop.loop.Loop._call_soon
  File "uvloop/loop.pyx", line 608, in uvloop.loop.Loop._call_soon_handle
  File "uvloop/loop.pyx", line 637, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
2019-07-30 20:18:10 ERROR (Thread-2030) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-07-30 20:18:10 ERROR (Thread-2030) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-07-30 20:18:10 ERROR (Thread-2030) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-07-30 20:18:10 ERROR (Thread-2030) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-07-30 20:18:10 ERROR (Thread-2030) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-07-30 20:18:10 ERROR (Thread-2030) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-07-30 20:18:10 ERROR (Thread-2030) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-07-30 20:18:10 ERROR (Thread-2030) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-07-30 20:18:10 ERROR (Thread-2030) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-07-30 20:18:10 ERROR (Thread-2030) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-07-30 20:18:10 ERROR (Thread-2030) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-07-30 20:18:10 ERROR (Thread-2030) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-07-30 20:18:10 ERROR (Thread-2030) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2019-07-30 20:18:13 ERROR (SyncWorker_11) [concurrent.futures] exception calling callback for <Future at 0x7fb65e2c0790 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "uvloop/loop.pyx", line 1261, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 604, in uvloop.loop.Loop._call_soon
  File "uvloop/loop.pyx", line 608, in uvloop.loop.Loop._call_soon_handle
  File "uvloop/loop.pyx", line 637, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
```

**Comment by ludeeus** [comment]
Looks like you had a combination of issues, one with HACS where GitHub had server issues (returning Server Error) and one with `media_player.lounge_av_rx` when they happened at the same time it was too much and the event loop was closed.
