### ISSUE TITLE
Startup crash - AttributeError: 'NoneType' object has no attribute 'published_at'

### ISSUE THREAD

**Issue by JurajNyiri** [custom-components/hacs#356]
## Version of HACS

0.12.1

## Describe the bug

While starting home assistant with HACS, HACS loads into a state where it is saying background process still running and it is stuck there. I think this is caused by an incorrect response from github (missing published_at) or some component update. There is a visible update for "Start Spotify on chromecast" saying there is a version 2.0.0.b1 released and my current is commit bc3af41 - repo https://github.com/fondberg/spotcast . When I click any other component it loads, when I click this one it fails with 500. Clicking settings, custom repositories is stuck on "Loading custom repositories...".

## Debug log

```
2019-07-30 23:20:21 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 71, in startup_tasks
    await self.recuring_tasks_installed(True)
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 279, in recuring_tasks_installed
    await repository.update()
  File "/config/custom_components/hacs/repositories/hacsrepositoryintegration.py", line 42, in update
    if await self.common_update():
  File "/config/custom_components/hacs/repositories/hacsrepositorybase.py", line 174, in common_update
    self.last_updated = await self.return_last_update()
  File "/config/custom_components/hacs/repositories/hacsrepositorybase.py", line 468, in return_last_update
    temp = self.last_release_object.published_at
AttributeError: 'NoneType' object has no attribute 'published_at'

```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 216, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 115, in handle
    result = await result
  File "/config/custom_components/hacs/http.py", line 47, in get
    response = await response.response(self)
  File "/config/custom_components/hacs/http.py", line 170, in response
    await repository.update()
  File "/config/custom_components/hacs/repositories/hacsrepositoryintegration.py", line 42, in update
    if await self.common_update():
  File "/config/custom_components/hacs/repositories/hacsrepositorybase.py", line 174, in common_update
    self.last_updated = await self.return_last_update()
  File "/config/custom_components/hacs/repositories/hacsrepositorybase.py", line 468, in return_last_update
    temp = self.last_release_object.published_at
AttributeError: 'NoneType' object has no attribute 'published_at'
```

## Other notes

Backup raspberry pi which is still running HACS 0.11.1 works flawlessly even with this update, so it has to be a recent change. It is detecting this:

Installed commit: bc3af41
Available commit: beb1f74

Digging further I found out that last_release_object for that repo is also None.

**Comment by ludeeus** [comment]
It looks like that repository at some point had releases, but they are not there anymore...
To fix it go into the `.storage/hacs` file and remove the part for spotcast.
After you have done that, restart HA.
When it have started you should be able to add it back again.

**Comment by JurajNyiri** [comment]
Thank you, that worked.
I think this scenario should still be handled correctly by code automatically, therefore I am not closing this issue.

**Comment by ludeeus** [comment]
It is already fixed in `next`
