### ISSUE TITLE
HACS doesn't start up anymore

### ISSUE THREAD

**Issue by ljmerza** [custom-components/hacs#360]
## Version of HACS
0.12.1

## Describe the bug
HACS crashes on hass start up starting just now.

## Debug log

```text
2019-07-31 14:22:59 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hacs fails
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/hacs/sensor.py", line 23, in async_update
    if hacs.store.task_running:
AttributeError: 'NoneType' object has no attribute 'task_running'
```

**Comment by ludeeus** [comment]
paste the _full_ startup log (with DEBUG) (not just the sensor)

**Comment by frenck** [comment]
I cannot provide a debug right now, however, I do see the same issue.
Additional information that I can provide at this point: I'm running HA 0.97b0.

**Comment by ludeeus** [comment]
I _think_ I have solved all startup issues (by adding retry logic) in the next version (both for config_flow and yaml configurations)
A pre-release (beta) of that _should_ be public later today.
