### ISSUE TITLE
Store: First "Airly" crashes system [SOLVED]

### ISSUE THREAD

**Issue by 3ative** [custom-components/hacs#365]
## Version of HACS
Latest - everything

## Describe the bug
In store > APPDAEMON APPS there are two "Airly" intergrations. Clicking the first one locks up HA completely. Which then requires a VM restart to get HA working again.

![Capture](https://user-images.githubusercontent.com/51385971/62285567-c3162280-b44d-11e9-9fa7-251c830b7d49.JPG)

Log file also shows this:
![Capture1](https://user-images.githubusercontent.com/51385971/62285594-d2956b80-b44d-11e9-972c-152537f3face.JPG)

## Debug log

Just some of the log entries - I'm guessing you don't need all 9000+ of them :)
```text

2019-08-01 11:06:41 ERROR (MainThread) 2019-08-01 11:06:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140386812189392] Client exceeded max pending messages [2]: 512
2019-08-01 11:06:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140386787182800] Client exceeded max pending messages [2]: 512
2019-08-01 11:06:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140386812189392] Client exceeded max pending messages [2]: 512
2019-08-01 11:06:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140386787182800] Client exceeded max pending messages [2]: 512
2019-08-01 11:06:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140386812189392] Client exceeded max pending messages [2]: 512
2019-08-01 11:06:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140386787182800] Client exceeded max pending messages [2]: 512
2019-08-01 11:06:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140386812189392] Client exceeded max pending messages [2]: 512
2019-08-01 11:06:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140386787182800] Client exceeded max pending messages [2]: 512
2019-08-01 11:06:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140386812189392] Client exceeded max pending messages [2]: 512
2019-08-01 11:06:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140386787182800] Client exceeded max pending messages [2]: 512
2019-08-01 11:06:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140386812189392] Client exceeded max pending messages [2]: 512
2019-08-01 11:06:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140386787182800] Client exceeded max pending messages [2]: 512
2019-08-01 11:06:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140386812189392] Client exceeded max pending messages [2]: 512
2019-08-01 11:06:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140386787182800] Client exceeded max pending messages [2]: 512
2019-08-01 11:06:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140386812189392] Client exceeded max pending messages [2]: 512

```

**Comment by ludeeus** [comment]
How did you end up with two?
HACS does not use WS, so it's a bit strange that you get issues with it...

If you go to "Settings" is there an Airly under "Custom repositories"? if it is, remove it.

**Comment by 3ative** [comment]
@ludeeus 
Know idea how I got two, it's just there! - I guess I'm special LMAO

Just found this, in the logs:
```
2019-08-01 11:32:39 ERROR (MainThread) [custom_components.hacs] bieniu/ha-airly - apps does not exist in the repository.
2019-08-01 11:33:07 WARNING (MainThread) [custom_components.hacs.template] Error rendering info template 'value' is undefined
2019-08-01 11:33:59 WARNING (MainThread) [custom_components.hacs.template] Error rendering info template 'states' is undefined
2019-08-01 11:36:43 WARNING (MainThread) [custom_components.hacs.template] Error rendering info template 'trigger' is undefined
2019-08-01 11:36:44 WARNING (MainThread) [custom_components.hacs.template] Error rendering info template 'trigger' is undefined
```

The only Custom repositories I have is: 

![Capture3](https://user-images.githubusercontent.com/51385971/62287217-52710500-b451-11e9-9077-57c5d65816a3.JPG)

I removed it, restarted.. now these have shown up:

![Capture4](https://user-images.githubusercontent.com/51385971/62287383-a8de4380-b451-11e9-8eba-f75867216e8b.JPG)

**Comment by 3ative** [comment]
Edit: Clicked the 'Trash Can' to remove the first one and they all went away!
Restarted HA, no Custom repositories listed now.

Still two Airly entries in the store though.

**Comment by ludeeus** [comment]
Remove them both from `.storage/hacs`.
The correct one will appear again.

**Comment by 3ative** [comment]
I have 3...

![Capture5](https://user-images.githubusercontent.com/51385971/62288027-6158b700-b453-11e9-91c2-11928ce24549.JPG)

Should I remove all?

**Comment by ludeeus** [comment]
no no no
Do not remove the files.
Just the Airly references in the file `.storage/hacs` (without a number)

**Comment by 3ative** [comment]
Opps... Everything stopped working.

HACS tab shows this:
![Capture](https://user-images.githubusercontent.com/51385971/62291412-cc0df080-b45b-11e9-8f7f-ff7ed5557af0.JPG)

And none of my HACS installs are working, I.E. Button Card, Slider card, etc.

Got this in the log and judging by the first line, I'll have to wait for the limit to expire. :(
```
2019-08-01 12:46:42 WARNING (MainThread) [custom_components.hacs] GitHub Ratelimit error
2019-08-01 12:46:46 ERROR (MainThread) [homeassistant.components.mold_indicator.sensor] 
2019-08-01 12:46:46 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 56, in startup_tasks
    self.store.task_running = True
AttributeError: 'NoneType' object has no attribute 'task_running'
2019-08-01 12:47:14 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hacs fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/hacs/sensor.py", line 23, in async_update
    if hacs.store.task_running:
AttributeError: 'NoneType' object has no attribute 'task_running'
2019-08-01 12:47:45 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hacs fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/hacs/sensor.py", line 23, in async_update
    if hacs.store.task_running:
AttributeError: 'NoneType' object has no attribute 'task_running'
2019-08-01 12:48:15 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hacs fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/hacs/sensor.py", line 23, in async_update
    if hacs.store.task_running:
AttributeError: 'NoneType' object has no attribute 'task_running'
2019-08-01 12:48:46 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hacs fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/hacs/sensor.py", line 23, in async_update
    if hacs.store.task_running:
AttributeError: 'NoneType' object has no attribute 'task_running'
2019-08-01 12:49:17 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hacs fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/hacs/sensor.py", line 23, in async_update
    if hacs.store.task_running:
AttributeError: 'NoneType' object has no attribute 'task_running'
2019-08-01 12:49:47 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hacs fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/hacs/sensor.py", line 23, in async_update
    if hacs.store.task_running:
AttributeError: 'NoneType' object has no attribute 'task_running'
2019-08-01 12:50:17 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hacs fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/hacs/sensor.py", line 23, in async_update
    if hacs.store.task_running:
AttributeError: 'NoneType' object has no attribute 'task_running'
2019-08-01 12:50:48 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hacs fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/hacs/sensor.py", line 23, in async_update
    if hacs.store.task_running:
AttributeError: 'NoneType' object has no attribute 'task_running'
2019-08-01 12:51:18 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hacs fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/hacs/sensor.py", line 23, in async_update
    if hacs.store.task_running:
AttributeError: 'NoneType' object has no attribute 'task_running'
2019-08-01 12:51:48 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hacs fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/hacs/sensor.py", line 23, in async_update
    if hacs.store.task_running:
AttributeError: 'NoneType' object has no attribute 'task_running'
2019-08-01 12:52:18 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hacs fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/hacs/sensor.py", line 23, in async_update
    if hacs.store.task_running:
AttributeError: 'NoneType' object has no attribute 'task_running'
2019-08-01 12:52:49 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hacs fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/hacs/sensor.py", line 23, in async_update
    if hacs.store.task_running:
AttributeError: 'NoneType' object has no attribute 'task_running'
2019-08-01 12:53:20 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hacs fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/hacs/sensor.py", line 23, in async_update
    if hacs.store.task_running:
AttributeError: 'NoneType' object has no attribute 'task_running'
2019-08-01 12:53:51 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hacs fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/hacs/sensor.py", line 23, in async_update
    if hacs.store.task_running:
AttributeError: 'NoneType' object has no attribute 'task_running'
```

**Comment by ludeeus** [comment]
Correct, takes 1h

**Comment by 3ative** [comment]
Yeah, I saw that in the docs... oh well, I better go find something else to do. 
See you in an Hour. :D

**Comment by 3ative** [comment]
@ludeeus 
Everything back up and working correctly now.
