### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by MTrab** [custom-components/hacs#388]
## Version of HACS
0.12.1 and Next branch

## Describe the bug
Getting an error when starting HA, and HACS is not active

## Debug log

```
Error during setup of component hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 168, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/hacs/__init__.py", line 69, in async_setup
    await configure_hacs(hass, config[DOMAIN], config_dir)
  File "/config/custom_components/hacs/__init__.py", line 171, in configure_hacs
    hacs.store.restore_values()
  File "/config/custom_components/hacs/hacsbase/data.py", line 102, in restore_values
    store = self.read()
  File "/config/custom_components/hacs/hacsbase/data.py", line 41, in read
    content = json.loads(content)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 3520 column 32 (char 126960)
```

**Comment by MTrab** [comment]
Found this one - same as this: https://github.com/custom-components/hacs/issues/339
