### ISSUE TITLE
Setup fails after new installation: module aiogithubapi missing

### ISSUE THREAD

**Issue by garethhowell** [custom-components/hacs#421]
## Version of HACS
0.13.0

## Describe the bug
This is a new installation of hacs on a new installation of hassio 0.97.0.
I installed using the terminal. When I checked the config, I got no errors, but when I restarted hass, I got:
```
Package hacs setup failed. Component hacs does not exist
12:09 PM components/hassio/__init__.py (ERROR) - message first occured at 11:18 AM and shows up 9 times
Error loading custom_components.hacs. Make sure all dependencies are installed
12:09 PM custom_components/hacs/__init__.py (ERROR) - message first occured at 11:18 AM and shows up 11 times
```

## Debug log

```
2019-08-13 12:24:07 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.hacs. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 355, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/hacs/__init__.py", line 23, in <module>
    from aiogithubapi import (
ModuleNotFoundError: No module named 'aiogithubapi'
2019-08-13 12:24:08 ERROR (MainThread) [homeassistant.components.hassio] Package hacs setup failed. Component hacs does not exist
```

Add your logs here.

```

**Comment by ludeeus** [comment]
Try restarting again, HA should install all dependencies if your network is ok

**Comment by garethhowell** [comment]
Thanks, that worked.
I wonder if a warning in the installation docs might be in order?

Gareth
