### ISSUE TITLE
(first time setup) Invalid syntax when cheking conf 

### ISSUE THREAD

**Issue by poofyteddy** [custom-components/hacs#451]
## Version of HACS
 0.13.2
## Describe the bug
Hi, i just tried to install hacs for the first time.
I did it without a git clone, juste by downloading the latest release tar.gz
when i tried to do a restart of HA in order to enable HACS, i got this error :
```
me@myserver:~$ sudo -u homeassistant /srv/homeassistant/bin/hass --script check_config

INFO:homeassistant.util.package:Attempting install of aiofiles==0.4.0                                                                                                                                              
INFO:homeassistant.util.package:Attempting install of backoff==1.8.0                                                                                                                                               
INFO:homeassistant.util.package:Attempting install of aiogithubapi==0.2.0                                                                                                                                          
INFO:homeassistant.util.package:Attempting install of integrationhelper==0.2.2                                                                                                                                     
ERROR:homeassistant.scripts.check_config:BURB                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                                 
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/scripts/check_config.py", line 202, in check                                                                                                  
    async_check_ha_config_file(hass))                                                                                                                                                                              
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete                                                                                                                                
    return future.result()                                                                                                                                                                                         
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result                                                                                                                                                
    raise self._exception                                                                                                                                                                                          
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step                                                                                                                                                   
    result = coro.send(None)                                                                                                                                                                                       
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/check_config.py", line 112, in async_check_ha_config_file                                                                             
    component = integration.get_component()                                                                                                                                                                        
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 211, in get_component                                                                                                        
    cache[self.domain] = importlib.import_module(self.pkg_path)                                                                                                                                                    
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module                                                                                                                                      
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                                                    
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import                                                                                                                                                   
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load                                                                                                                                                
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked                                                                                                                                       
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 109
    hacs.logger.debug(f"Configuration type: {hacs.configuration.config_type}")
                                                                            ^
SyntaxError: invalid syntax
Fatal error while loading config: invalid syntax (__init__.py, line 109)
Failed config
  General Errors:
    - invalid syntax (__init__.py, line 109)

Successful config (partial)
```
A syntax error seam ood because clearly it shouldn't work for anyone ... so what am i missing ?
obviously the restart didn't append after that :)

**Comment by ludeeus** [comment]
This integration requires Home Assistant version 0.97+ which also requires Python 3.6+
https://hacs.netlify.com/installation/manual/#prerequisittes

**Comment by poofyteddy** [comment]
sorry, i didn't took the time to check because i had updated HA last night, so "obviously i'm up to date" ... I'll be looking for a way to get python 3.6 on debian stretch then. sorry for your time.
