### ISSUE TITLE
TimeoutError for aiogithubapi.repository.get_contents()

### ISSUE THREAD

**Issue by DMQ8** [custom-components/hacs#468]
## Version of HACS

Installed version: | 0.13.2
-- | --

## Describe the bug

This is a new install for HACS, Im using Docker on Synology NAS. Home Assistant is V0.97.2
 Under Community, Overview, Im getting the following msg forever:
"Background task running, this page will reload when it's done."

Also under CUSTOM REPOSITORIES im getting the msg:
"Loading custom repositories..."

As this is a new installation there is not much in my configuration.yaml but the following is what I have for HACS:
hacs:
  token: !secret HACS_github
  appdaemon: true
  python_script: true
  theme: true

I'm not sure if those three need to be set "true" in my case.

I can see Items in store and I can also search, but the "background task" msg never end. I tried to restart Home Assistant and tried to reinstall HACS without any success.

I'm also getting the following events/errors:
Error doing job: Task exception was never retrieved
12:16 AM custom_components/hacs/repositories/integration.py (ERROR)
Giving up get_contents(...) after 5 tries (concurrent.futures._base.TimeoutError)
12:16 AM __main__.py (ERROR)

## Debug log

```text

2019-08-22 00:16:58 ERROR (MainThread) [backoff] Giving up get_contents(...) after 5 tries (concurrent.futures._base.TimeoutError)
2019-08-22 00:16:58 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiogithubapi/repository.py", line 84, in get_contents
    response = await self.session.get(url, headers=self.headers, params=params)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 497, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 844, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 588, in read
    await self._waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 154, in startup_tasks
    await self.load_known_repositories()
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 283, in load_known_repositories
    await self.register_repository(repo, category)
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 131, in register_repository
    await repository.registration()
  File "/config/custom_components/hacs/repositories/integration.py", line 72, in registration
    if not await self.validate_repository():
  File "/config/custom_components/hacs/repositories/integration.py", line 60, in validate_repository
    if not await self.get_manifest():
  File "/config/custom_components/hacs/repositories/integration.py", line 118, in get_manifest
    manifest = await self.repository_object.get_contents(manifest_path, self.ref)
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aiogithubapi/repository.py", line 102, in get_contents
    contents.append(AIOGithubRepositoryContent(content))
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

```
Thanks for your support.

**Comment by DMQ8** [comment]
Also here is what it shows that is related to HACS in home-assistant.log :

```
INFO (MainThread) [hacs.repository.integration.custom-components.hacs] Registration complete
INFO (MainThread) [homeassistant.setup] Setup of domain hacs took 4.7 seconds.
INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hacs
INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 6.91s
INFO (MainThread) [homeassistant.core] Starting Home Assistant
INFO (MainThread) [hacs] Loading known repositories
INFO (MainThread) [homeassistant.core] Timer:starting
INFO (MainThread) [hacs.repository.appdaemon.apop880.SmartThings-Button] Registration complete
INFO (MainThread) [hacs.repository.appdaemon.apop880.White-Noise] Registration complete
INFO (MainThread) [hacs.repository.appdaemon.apop880.Night-Mode] Registration complete
INFO (MainThread) [hacs.repository.appdaemon.apop880.config-check] Registration complete
INFO (MainThread) [hacs.repository.appdaemon.benleb.ad-automoli] Registration complete
INFO (MainThread) [hacs.repository.appdaemon.benleb.ad-batterycheck] Registration complete
INFO (MainThread) [hacs.repository.appdaemon.benleb.ad-healthcheck] Registration complete
INFO (MainThread) [hacs.repository.appdaemon.benleb.ad-notifreeze] Registration complete
INFO (MainThread) [hacs.repository.appdaemon.bieniu.ha-ad-airly] Registration complete
INFO (MainThread) [hacs.repository.appdaemon.bieniu.ha-ad-thermostats-update] Registration complete
INFO (MainThread) [hacs.repository.appdaemon.ludeeus.ad-watchdog] Registration complete
INFO (MainThread) [hacs.repository.appdaemon.eifinger.appdaemon-deconz-xiaomi-button] Registration complete
INFO (MainThread) [hacs.repository.integration.DSorlov.hasl-platform] Registration complete
INFO (MainThread) [hacs.repository.integration.StyraHem.ShellyForHASS] Registration complete
INFO (MainThread) [hacs.repository.integration.isabellaalstrom.sensor.krisinformation] Registration complete
INFO (MainThread) [hacs.repository.integration.JurajNyiri.HomeAssistant-Tavos] Registration complete
INFO (MainThread) [hacs.repository.integration.JurajNyiri.HomeAssistant-Atrea] Registration complete
INFO (MainThread) [hacs.repository.integration.JurajNyiri.HomeAssistant-qBitTorrentAlternativeSpeed] Registration complete
INFO (MainThread) [hacs.repository.integration.TimSoethout.goodwe-sems-home-assistant] Registration complete
INFO (MainThread) [hacs.repository.integration.bramkragten.lyric] Registration complete
INFO (MainThread) [hacs.repository.integration.bramkragten.mind] Registration complete
INFO (MainThread) [hacs.repository.integration.bouwew.sems2mqtt] Registration complete
INFO (MainThread) [hacs.repository.integration.akasma74.Hass-Custom-Alarm] Registration complete
INFO (MainThread) [hacs.repository.integration.keatontaylor.alexa_media_player] Registration complete
INFO (MainThread) [hacs.repository.integration.albertogeniola.meross-homeassistant] Registration complete
INFO (MainThread) [hacs.repository.integration.mudape.iphonedetect] Registration complete
INFO (MainThread) [hacs.repository.integration.bertbert72.HomeAssistant_VirginTivo] Registration complete
INFO (MainThread) [hacs.repository.integration.nstrelow.ha_philips_android_tv] Registration complete
INFO (MainThread) [hacs.repository.integration.rsnodgrass.hass-integrations] Registration complete
INFO (MainThread) [hacs.repository.integration.Ceerbeerus.beerbolaget] Registration complete
INFO (MainThread) [hacs.repository.integration.thomasloven.hass-browser_mod] Registration complete
INFO (MainThread) [hacs.repository.integration.thomasloven.hass-lovelace_gen] Registration complete
INFO (MainThread) [hacs.repository.integration.thomasloven.hass-favicon] Registration complete
INFO (MainThread) [hacs.repository.integration.claytonjn.hass-circadian_lighting] Registration complete
INFO (MainThread) [hacs.repository.integration.xMrVizzy.Philips-AirPurifier] Registration complete
INFO (MainThread) [hacs.repository.integration.jomwells.ambilights] Registration complete
INFO (MainThread) [hacs.repository.integration.jomwells.ambihue] Registration complete
INFO (MainThread) [hacs.repository.integration.jomwells.ambilight-yeelight] Registration complete
INFO (MainThread) [hacs.repository.integration.MatthewFlamm.nwsradar] Registration complete
INFO (MainThread) [hacs.repository.integration.Paul-dH.Home-Assisant-Sensor-OvApi] Registration complete
INFO (MainThread) [hacs.repository.integration.rt400.School-Vacation] Registration complete
INFO (MainThread) [hacs.repository.integration.xirixiz.Home-Assistant-Sensor-Afvalwijzer] Registration complete
INFO (MainThread) [hacs.repository.integration.bieniu.ha-airly] Registration complete
INFO (MainThread) [hacs.repository.integration.bieniu.ha-gios] Registration complete
INFO (MainThread) [hacs.repository.integration.DavidFW1960.bom_forecast] Registration complete
INFO (MainThread) [hacs.repository.integration.legrego.homeassistant-elasticsearch] Registration complete
INFO (MainThread) [hacs.repository.integration.kalanda.homeassistant-aemet-sensor] Registration complete
INFO (MainThread) [hacs.repository.integration.basschipper.homeassistant-generic-hygrostat] Registration complete
INFO (MainThread) [hacs.repository.integration.claudegel.sinope-1] Registration complete
INFO (MainThread) [hacs.repository.integration.claudegel.sinope-gt125] Registration complete
INFO (MainThread) [hacs.repository.integration.tybritten.ical-sensor-homeassistant] Registration complete
INFO (MainThread) [hacs.repository.integration.Martinvdm.garbage-nissewaard-homeassistant] Registration complete
INFO (MainThread) [hacs.repository.integration.RobHofmann.HomeAssistant-GreeClimateComponent] Registration complete
INFO (MainThread) [hacs.repository.integration.pippyn.Home-Assistant-Sensor-Afvalbeheer] Registration complete
INFO (MainThread) [hacs.repository.integration.pippyn.Home-Assistant-Sensor-Groningen-Afvalwijzer] Registration complete
INFO (MainThread) [backoff] Backing off get_contents(...) for 0.1s (concurrent.futures._base.TimeoutError)
INFO (MainThread) [backoff] Backing off get_contents(...) for 1.1s (concurrent.futures._base.TimeoutError)
INFO (MainThread) [backoff] Backing off get_contents(...) for 3.4s (concurrent.futures._base.TimeoutError)
INFO (MainThread) [backoff] Backing off get_contents(...) for 4.3s (concurrent.futures._base.TimeoutError)
ERROR (MainThread) [backoff] Giving up get_contents(...) after 5 tries (concurrent.futures._base.TimeoutError)
ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiogithubapi/repository.py", line 84, in get_contents
    response = await self.session.get(url, headers=self.headers, params=params)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 497, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 844, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 588, in read
    await self._waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 154, in startup_tasks
    await self.load_known_repositories()
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 283, in load_known_repositories
    await self.register_repository(repo, category)
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 131, in register_repository
    await repository.registration()
  File "/config/custom_components/hacs/repositories/integration.py", line 72, in registration
    if not await self.validate_repository():
  File "/config/custom_components/hacs/repositories/integration.py", line 60, in validate_repository
    if not await self.get_manifest():
  File "/config/custom_components/hacs/repositories/integration.py", line 118, in get_manifest
    manifest = await self.repository_object.get_contents(manifest_path, self.ref)
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aiogithubapi/repository.py", line 102, in get_contents
    contents.append(AIOGithubRepositoryContent(content))
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
```

**Comment by ludeeus** [comment]
Added more handling of this in <https://github.com/custom-components/hacs/releases/tag/0.14.0b0>
