### ISSUE TITLE
HACS hangs up my Home Assistant

### ISSUE THREAD

**Issue by bieniu** [custom-components/hacs#473]
##  Version of HACS
0.13.2

## Version of HA
0.97.2

## Describe the bug
In HACS I went to Alexa Media Player page and then error occurred (the page wasn't load):
```
2019-08-23 08:59:51 ERROR (MainThread) [hass_nabucasa.iot] Unexpected error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/real_ip.py", line 37, in real_ip_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 69, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 228, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 124, in handle
    result = await result
  File "/home/homeassistant/.homeassistant/custom_components/hacs/api.py", line 43, in post
    response = await response.response(self)
  File "/home/homeassistant/.homeassistant/custom_components/hacs/api.py", line 184, in response
    await repository.update_repository()
  File "/home/homeassistant/.homeassistant/custom_components/hacs/repositories/integration.py", line 86, in update_repository
    await self.common_update()
  File "/home/homeassistant/.homeassistant/custom_components/hacs/repositories/repository.py", line 335, in common_update
    await self.get_info_md_content()
  File "/home/homeassistant/.homeassistant/custom_components/hacs/repositories/repository.py", line 449, in get_info_md_content
    root = await self.repository_object.get_contents("", self.ref)
  File "/srv/homeassistant/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiogithubapi/repository.py", line 86, in get_contents
    raise AIOGitHubException(f"GitHub returned {response.status} for {url}")
aiogithubapi.exceptions.AIOGitHubException: GitHub returned 404 for https://api.github.com/repos/keatontaylor/alexa_media_player/contents/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/hass_nabucasa/iot.py", line 86, in connect
    await self._handle_connection()
  File "/srv/homeassistant/lib/python3.7/site-packages/hass_nabucasa/iot.py", line 186, in _handle_connection
    msg = await client.receive()
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/client_ws.py", line 227, in receive
    msg = await self._reader.read()
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/streams.py", line 628, in read
    return await super().read()
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/streams.py", line 588, in read
    await self._waiter
concurrent.futures._base.CancelledError
```
After that all integrations that use asyncio had a lot of errors and HA hang up:
```
2019-08-23 08:59:51 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.mibox fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/real_ip.py", line 37, in real_ip_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 69, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 228, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 124, in handle
    result = await result
  File "/home/homeassistant/.homeassistant/custom_components/hacs/api.py", line 43, in post
    response = await response.response(self)
  File "/home/homeassistant/.homeassistant/custom_components/hacs/api.py", line 184, in response
    await repository.update_repository()
  File "/home/homeassistant/.homeassistant/custom_components/hacs/repositories/integration.py", line 86, in update_repository
    await self.common_update()
  File "/home/homeassistant/.homeassistant/custom_components/hacs/repositories/repository.py", line 335, in common_update
    await self.get_info_md_content()
  File "/home/homeassistant/.homeassistant/custom_components/hacs/repositories/repository.py", line 449, in get_info_md_content
    root = await self.repository_object.get_contents("", self.ref)
  File "/srv/homeassistant/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiogithubapi/repository.py", line 86, in get_contents
    raise AIOGitHubException(f"GitHub returned {response.status} for {url}")
aiogithubapi.exceptions.AIOGitHubException: GitHub returned 404 for https://api.github.com/repos/keatontaylor/alexa_media_player/contents/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 249, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 419, in async_device_update
    await self.hass.async_add_executor_job(self.update)
concurrent.futures._base.CancelledError
2019-08-23 09:00:02 ERROR (Thread-6) [xiaomi_gateway] Cannot process multicast message: {'cmd': 'report', 'model': 'sensor_motion.aq2', 'sid': '158d0001e16389', 'short_id': 54307, 'data': '{"no_motion":"600"}'}
2019-08-23 09:00:04 ERROR (Thread-6) [xiaomi_gateway] Cannot process multicast message: {'cmd': 'report', 'model': 'motion', 'sid': '158d000121c604', 'short_id': 51859, 'data': '{"status":"motion"}'}
2019-08-23 09:00:06 ERROR (Thread-6) [xiaomi_gateway] Cannot process multicast message: {'cmd': 'report', 'model': 'sensor_motion.aq2', 'sid': '158d0001e16389', 'short_id': 54307, 'data': '{"lux":"56"}'}
2019-08-23 09:00:06 ERROR (Thread-6) [xiaomi_gateway] Cannot process multicast message: {'cmd': 'report', 'model': 'sensor_motion.aq2', 'sid': '158d0001e16389', 'short_id': 54307, 'data': '{"status":"motion"}'}
2019-08-23 09:00:09 ERROR (Thread-6) [xiaomi_gateway] Cannot process multicast message: {'cmd': 'report', 'model': 'sensor_motion.aq2', 'sid': '158d0001e16358', 'short_id': 57065, 'data': '{"lux":"21"}'}
2019-08-23 09:00:09 ERROR (Thread-6) [xiaomi_gateway] Cannot process multicast message: {'cmd': 'report', 'model': 'sensor_motion.aq2', 'sid': '158d0001e16358', 'short_id': 57065, 'data': '{"status":"motion"}'}
2019-08-23 09:00:49 ERROR (Thread-6) [xiaomi_gateway] Cannot process multicast message: {'cmd': 'report', 'model': 'sensor_motion.aq2', 'sid': '158d0002b935e7', 'short_id': 28603, 'data': '{"no_motion":"1200"}'}
2019-08-23 09:01:14 ERROR (Dummy-8) [openzwave] Error in manager callback
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 952, in zwcallback
    self._handle_value_changed(args)
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 1504, in _handle_value_changed
    'value' : self.nodes[args['nodeId']].values[args['valueId']['id']]})
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 175, in network_node_changed
    self.node_changed()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 217, in node_changed
    self.maybe_schedule_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 77, in maybe_schedule_update
    self.hass.add_job(self._schedule_update)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 287, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-08-23 09:01:14 ERROR (Dummy-8) [openzwave] Error in manager callback
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 952, in zwcallback
    self._handle_value_changed(args)
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 1504, in _handle_value_changed
    'value' : self.nodes[args['nodeId']].values[args['valueId']['id']]})
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 175, in network_node_changed
    self.node_changed()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 217, in node_changed
    self.maybe_schedule_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 77, in maybe_schedule_update
    self.hass.add_job(self._schedule_update)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 287, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-08-23 09:01:15 ERROR (Dummy-8) [openzwave] Error in manager callback
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 952, in zwcallback
    self._handle_value_changed(args)
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 1504, in _handle_value_changed
    'value' : self.nodes[args['nodeId']].values[args['valueId']['id']]})
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 175, in network_node_changed
    self.node_changed()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 217, in node_changed
    self.maybe_schedule_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 77, in maybe_schedule_update
    self.hass.add_job(self._schedule_update)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 287, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-08-23 09:01:15 ERROR (Dummy-8) [openzwave] Error in manager callback
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 952, in zwcallback
    self._handle_value_changed(args)
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 1504, in _handle_value_changed
    'value' : self.nodes[args['nodeId']].values[args['valueId']['id']]})
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 175, in network_node_changed
    self.node_changed()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 217, in node_changed
    self.maybe_schedule_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 77, in maybe_schedule_update
    self.hass.add_job(self._schedule_update)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 287, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-08-23 09:01:15 ERROR (Dummy-8) [openzwave] Error in manager callback
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 982, in zwcallback
    self._handle_notification(args)
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 1576, in _handle_notification
    **{'network': self, 'args': args})
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 175, in network_node_changed
    self.node_changed()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 217, in node_changed
    self.maybe_schedule_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 77, in maybe_schedule_update
    self.hass.add_job(self._schedule_update)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 287, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-08-23 09:01:15 ERROR (Dummy-8) [openzwave] Error in manager callback
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 982, in zwcallback
    self._handle_notification(args)
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 1576, in _handle_notification
    **{'network': self, 'args': args})
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 175, in network_node_changed
    self.node_changed()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 217, in node_changed
    self.maybe_schedule_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 77, in maybe_schedule_update
    self.hass.add_job(self._schedule_update)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 287, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-08-23 09:01:21 ERROR (Thread-6) [xiaomi_gateway] Cannot process multicast message: {'cmd': 'heartbeat', 'model': 'motion', 'sid': '158d000121c604', 'short_id': 51859, 'data': '{"voltage":3035}'}
2019-08-23 09:01:38 ERROR (Dummy-8) [openzwave] Error in manager callback
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 952, in zwcallback
    self._handle_value_changed(args)
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 1504, in _handle_value_changed
    'value' : self.nodes[args['nodeId']].values[args['valueId']['id']]})
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 175, in network_node_changed
    self.node_changed()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 217, in node_changed
    self.maybe_schedule_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 77, in maybe_schedule_update
    self.hass.add_job(self._schedule_update)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 287, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-08-23 09:01:38 ERROR (Dummy-8) [openzwave] Error in manager callback
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 952, in zwcallback
    self._handle_value_changed(args)
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 1504, in _handle_value_changed
    'value' : self.nodes[args['nodeId']].values[args['valueId']['id']]})
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 175, in network_node_changed
    self.node_changed()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 217, in node_changed
    self.maybe_schedule_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 77, in maybe_schedule_update
    self.hass.add_job(self._schedule_update)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 287, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-08-23 09:01:38 ERROR (Dummy-8) [openzwave] Error in manager callback
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 952, in zwcallback
    self._handle_value_changed(args)
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 1504, in _handle_value_changed
    'value' : self.nodes[args['nodeId']].values[args['valueId']['id']]})
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 175, in network_node_changed
    self.node_changed()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 217, in node_changed
    self.maybe_schedule_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 77, in maybe_schedule_update
    self.hass.add_job(self._schedule_update)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 287, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-08-23 09:01:38 ERROR (Dummy-8) [openzwave] Error in manager callback
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 952, in zwcallback
    self._handle_value_changed(args)
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 1504, in _handle_value_changed
    'value' : self.nodes[args['nodeId']].values[args['valueId']['id']]})
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 175, in network_node_changed
    self.node_changed()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 217, in node_changed
    self.maybe_schedule_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 77, in maybe_schedule_update
    self.hass.add_job(self._schedule_update)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 287, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-08-23 09:01:38 ERROR (Dummy-8) [openzwave] Error in manager callback
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 982, in zwcallback
    self._handle_notification(args)
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 1576, in _handle_notification
    **{'network': self, 'args': args})
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 175, in network_node_changed
    self.node_changed()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 217, in node_changed
    self.maybe_schedule_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 77, in maybe_schedule_update
    self.hass.add_job(self._schedule_update)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 287, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-08-23 09:01:38 ERROR (Dummy-8) [openzwave] Error in manager callback
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 982, in zwcallback
    self._handle_notification(args)
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/network.py", line 1576, in _handle_notification
    **{'network': self, 'args': args})
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/srv/homeassistant/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 175, in network_node_changed
    self.node_changed()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 217, in node_changed
    self.maybe_schedule_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/node_entity.py", line 77, in maybe_schedule_update
    self.hass.add_job(self._schedule_update)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 287, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by ludeeus** [comment]
That is wierd...

https://github.com/custom-components/hacs/blob/ae876f6cddb9c433aee74358978e70d79a1798a3/custom_components/hacs/repositories/repository.py#L449

Should be caught by:

https://github.com/custom-components/hacs/blob/ae876f6cddb9c433aee74358978e70d79a1798a3/custom_components/hacs/repositories/repository.py#L473

**Comment by bieniu** [comment]
I turned on debug log and tried to reproduce this error after restart, but so far without luck.

**Comment by ludeeus** [comment]
Same here, I'm not able to reproduce it...

**Comment by to4ko** [comment]
same errors pupping up once in a while - can be right after Hassio restart\machine restart or after 2 days uptime. Only container restart via portainer helps.

**Comment by ludeeus** [comment]
Added exception for `AIOGitHubException` in <https://github.com/custom-components/hacs/releases/tag/0.14.0b0>
