### ISSUE TITLE
500 Internal Server Error when trying to open HACS

### ISSUE THREAD

**Issue by chierichetto** [custom-components/hacs#501]
## Version of HACS

0.13.2

## Describe the bug
Whenever i try to open HACS, i get 500 Internal Server Error. HACS stopped working some time ago, so i was on an pretty old version i think. Downloaded 0.13 and removed everything inside storage that had something to do with HACS, and now i get this error.

## Debug log

```text

erlend@erlend-VirtualBox:/usr/share/hassio$ tail -f /usr/share/hassio/homeassistant/home-assistant.log | grep hacs
2019-09-03 19:38:07 DEBUG (MainThread) [custom_components.hacs.blacklist] tenly2000/HomeAssistant-Places
2019-09-03 19:38:07 DEBUG (MainThread) [custom_components.hacs.blacklist] Rocka84/dual-gauge-card
2019-09-03 19:38:09 INFO (MainThread) [custom_components.hacs.integration] Fetching updated repository list
2019-09-03 19:38:10 INFO (MainThread) [custom_components.hacs.plugin] Fetching updated repository list
2019-09-03 19:38:19 DEBUG (MainThread) [custom_components.hacs.sensor.pending_update] custom-components/hacs
2019-09-03 19:38:49 DEBUG (MainThread) [custom_components.hacs.sensor.pending_update] custom-components/hacs
2019-09-03 19:39:20 DEBUG (MainThread) [custom_components.hacs.sensor.pending_update] custom-components/hacs
2019-09-03 19:39:51 DEBUG (MainThread) [custom_components.hacs.sensor.pending_update] custom-components/hacs
2019-09-03 19:40:22 DEBUG (MainThread) [custom_components.hacs.sensor.pending_update] custom-components/hacs
2019-09-03 19:40:22 DEBUG (MainThread) [custom_components.hacs.web] Endpoint (overview) called
  File "/config/custom_components/hacs12/http.py", line 47, in get
  File "/config/custom_components/hacs12/http.py", line 156, in response
  File "/config/custom_components/hacs12/http.py", line 62, in render
    return template.render({"hacs": self, "location": location, "repository": repository, "message": message})
  File "/config/custom_components/hacs/frontend/templates/overviews.html", line 2, in top-level template code
  File "/config/custom_components/hacs/frontend/templates/base.html", line 1, in top-level template code
    {% set progressbar = 'block' if hacs.system.status.background_task else 'none' %}
jinja2.exceptions.UndefinedError: 'custom_components.hacs12.http.HacsWebResponse object' has no attribute 'system'
2019-09-03 19:40:53 DEBUG (MainThread) [custom_components.hacs.sensor.pending_update] custom-components/hacs
```

**Comment by ludeeus** [comment]
you need to restart when changing the files

**Comment by chierichetto** [comment]
The problem sadly persists between reboots.
Any idea how i can start completely fresh?

**Comment by ludeeus** [comment]
That is not possible.
You get this error when you use new frontend files, and old backend.
If you restart the error is not there/different.

Restarting in the UI will not work if you have config issues.

**Comment by chierichetto** [comment]
You are right. Now i get a different error. Can you see what i have done wrong?

`2019-09-05 12:09:26 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 359, in get_provider
    module = sys.modules[moduleOrReq]
KeyError: 'custom_components.hacs.frontend'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 40, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 231, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 128, in handle
    result = await result
  File "/config/custom_components/hacs12/http.py", line 47, in get
    response = await response.response(self)
  File "/config/custom_components/hacs12/http.py", line 156, in response
    render = self.render('overviews', 'overview')
  File "/config/custom_components/hacs12/http.py", line 60, in render
    loader = Environment(loader=PackageLoader('custom_components.hacs.frontend'))
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 224, in __init__
    provider = get_provider(package_name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 361, in get_provider
    __import__(moduleOrReq)
  File "/config/custom_components/hacs/__init__.py", line 23, in 
    from aiogithubapi import (
ModuleNotFoundError: No module named 'aiogithubapi'`

**Comment by ludeeus** [comment]
It's not you, it's your HA instance that did not install a required module, try restarting a few times.

**Comment by ludeeus** [comment]
I guess that worked

**Comment by chierichetto** [comment]
Sorry, i've been busy the last couple of days.
I've restart HA mulitple times, but it's still not working.
I get this error in HA log on boot:
`Error importing platform config_flow from integration hacs to set up hacs config entry: No module named 'custom_components.hacs12.config_flow'
`
