### ISSUE TITLE
Error loading custom_components.hacs. Make sure all dependencies are installed

### ISSUE THREAD

**Issue by cierigabriele** [custom-components/hacs#531]
Hello my community is disappeared
```
Sun Sep 15 2019 13:21:43 GMT+0200 (Ora legale dell’Europa centrale)
Error loading custom_components.hacs. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 355, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 32, in <module>
    from .api import HacsAPI, HacsRunningTask
  File "/home/homeassistant/.homeassistant/custom_components/hacs/api.py", line 7, in <module>
    from .http import HacsWebResponse
ImportError: cannot import name 'HacsWebResponse' from 'custom_components.hacs.http' (/home/homeassistant/.homeassistant/custom_components/hacs/http.py)
```

**Comment by ludeeus** [comment]
You are missing one (or more files)
Redownload from the latest release, then restart.
https://github.com/custom-components/hacs/releases/latest
