### ISSUE TITLE
HACS 0.14.0 does not start

### ISSUE THREAD

**Issue by astrandb** [custom-components/hacs#552]
## Version of HACS
0.14.0  on HA 99.2

## Describe the bug
Upgraded from 0.14.0.b2 to 0.14.0. After that HACS does not start properly.

## Debug log

```text

Sat Sep 21 2019 12:28:33 GMT+0200 (centraleuropeisk sommartid)
Error during setup of component hacs
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 168, in _async_setup_component
    hass, processed_config
  File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 77, in async_setup
    await startup_wrapper_for_yaml(Hacs)
  File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 109, in startup_wrapper_for_yaml
    startup_result = await hacs_startup(hacs)
  File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 151, in hacs_startup
    if not await load_hacs_repository(hacs):
  File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 233, in load_hacs_repository
    await hacs().register_repository("custom-components/hacs", "integration")
  File "/home/homeassistant/.homeassistant/custom_components/hacs/hacsbase/__init__.py", line 131, in register_repository
    await repository.registration()
  File "/home/homeassistant/.homeassistant/custom_components/hacs/repositories/integration.py", line 81, in registration
    if not await self.validate_repository():
  File "/home/homeassistant/.homeassistant/custom_components/hacs/repositories/integration.py", line 39, in validate_repository
    await self.common_validate()
  File "/home/homeassistant/.homeassistant/custom_components/hacs/repositories/repository.py", line 287, in common_validate
    await self.get_releases()
  File "/home/homeassistant/.homeassistant/custom_components/hacs/repositories/repository.py", line 535, in get_releases
    prerelease=False, returnlimit=self.configuration.release_limit
  File "/home/homeassistant/.homeassistant/custom_components/hacs/hacsbase/configuration.py", line 103, in release_limit
    return self.options.get("release_limit", 5)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by nudded** [comment]
Workaround: specify the `options` in the configuration.

**Comment by ludeeus** [comment]
I guess you are using YAML to configure?

As a workaround add this to your config:

```yaml
hacs:
  ...
  options:
    release_limit: 5
```

**Comment by ludeeus** [comment]
0.14.1 fixes this
