### ISSUE TITLE
integration.py L66 (validate_repository): TypeError: 'AIOGithubRepositoryContent' object is not iterable

### ISSUE THREAD

**Issue by hellcry37** [custom-components/hacs#553]
## Version of HACS
0.14.1

## Describe the bug
First HACS fail after update to this version even if it was working ok via configuration.yaml. I've decided to remove everything and start clean:
1. removed from /config/.storage the following files:
hacs.2
hacs.3
hacs.4
hacs.hacs
hacs.installed
hacs.repositories
2. removed from /config/custom_components/
hacs folder
3. files were actually moved to another pc for backup proposes
4. commented in configuration.yaml hacs: entry
5. commented in secrets file token
6. restarted HA
7. after this I downloaded hacs from github and put corresponding folder in custom_components/ folder (without this step integration does not appear in HA integrations page
8. restart ha
9. setup hacs via integrations page

When I click on hacs (community on menu) i see "Background task running, this page will reload when it's done." and integrations appears like normal.

The actual problem is whatever I do after i install any of them after restarting HA process starts over and i got this error in logs

Ofc all that i installed before install is not there anymore

What I observed is files in .storage folder are not created anymore whatever I do
hacs.2
hacs.3
hacs.4
hacs.hacs
hacs.installed
hacs.repositories

Also whatever settings I change doesn't stick, gets reset after restarting ha.
## Debug log

```text

Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 154, in startup_tasks
    await self.load_known_repositories()
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 283, in load_known_repositories
    await self.register_repository(repo, category)
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 131, in register_repository
    await repository.registration()
  File "/config/custom_components/hacs/repositories/integration.py", line 81, in registration
    if not await self.validate_repository():
  File "/config/custom_components/hacs/repositories/integration.py", line 66, in validate_repository
    for filename in self.content.objects:
TypeError: 'AIOGithubRepositoryContent' object is not iterable


```

**Comment by Red-M** [comment]
Can confirm that I also get this exact same issue.

**Comment by ludeeus** [comment]
Paste the entire startup log

**Comment by Red-M** [comment]
```2019-09-22 00:30:46 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for smartir which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-09-22 00:30:46 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-09-22 00:30:46 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-09-22 00:30:46 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for breaking_changes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-09-22 00:30:49 ERROR (MainThread) [homeassistant.config] Unable to import spotcast: No module named 'pychromecast.controllers.homeassistant'
2019-09-22 00:30:49 ERROR (MainThread) [homeassistant.setup] Setup failed for spotcast: Invalid config.
2019-09-22 00:30:49 ERROR (SyncWorker_8) [homeassistant.components.octoprint] Endpoint: printer Failed to update OctoPrint status.   Error: HTTPConnectionPool(host='CENSORED', port=80): Max retries exceeded with url: /api/printer (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa1ae13d320>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019-09-22 00:30:49 ERROR (SyncWorker_8) [homeassistant.components.octoprint] Endpoint: job Failed to update OctoPrint status.   Error: HTTPConnectionPool(host='CENSORED', port=80): Max retries exceeded with url: /api/job (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa1ae13d0b8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019-09-22 00:30:53 ERROR (MainThread) [homeassistant.config] Unable to import cast: cannot import name 'APP_HOME_ASSISTANT' from 'pychromecast.config' (/home/CENSORED/.homeassistant/deps/lib/python3.7/site-packages/pychromecast/config.py)
2019-09-22 00:30:53 ERROR (MainThread) [homeassistant.setup] Setup failed for cast: Invalid config.
2019-09-22 00:30:53 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for radarr_upcoming_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-09-22 00:30:53 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sonarr_upcoming_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-09-22 00:30:56 ERROR (MainThread) [homeassistant.config] Platform error: sensor
Traceback (most recent call last):
  File "/home/CENSORED/.local/lib/python3.7/site-packages/homeassistant/config.py", line 757, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/home/CENSORED/.local/lib/python3.7/site-packages/homeassistant/loader.py", line 232, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/CENSORED/.homeassistant/custom_components/spotcast/__init__.py", line 6, in <module>
    from homeassistant.components.cast.media_player import KNOWN_CHROMECAST_INFO_KEY
  File "/home/CENSORED/.local/lib/python3.7/site-packages/homeassistant/components/cast/__init__.py", line 4, in <module>
    from . import home_assistant_cast
  File "/home/CENSORED/.local/lib/python3.7/site-packages/homeassistant/components/cast/home_assistant_cast.py", line 6, in <module>
    from pychromecast.controllers.homeassistant import HomeAssistantController
ModuleNotFoundError: No module named 'pychromecast.controllers.homeassistant'
2019-09-22 00:30:56 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for bom_forecast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-09-22 00:31:06 WARNING (MainThread) [homeassistant.components.sensor] Setup of platform bom_forecast is taking over 10 seconds.
2019-09-22 00:31:56 ERROR (MainThread) [homeassistant.components.sensor] Setup of platform bom_forecast is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2019-09-22 00:32:15 ERROR (SyncWorker_3) [homeassistant.components.plex] Plex server could not be reached, please verify host and port: [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))]
2019-09-22 00:36:49 ERROR (MainThread) [hacs] Tried to serve up '/home/CENSORED/.homeassistant/www/community/github-card/github-card.js.map' but it does not exist
2019-09-22 00:37:30 ERROR (SyncWorker_14) [homeassistant.components.plex] Plex server could not be reached, please verify host and port: [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))]
2019-09-22 00:39:30 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/CENSORED/.homeassistant/custom_components/hacs/hacsbase/__init__.py", line 203, in recuring_tasks_all
    await repository.update_repository()
  File "/home/CENSORED/.homeassistant/custom_components/hacs/repositories/integration.py", line 117, in update_repository
    for filename in self.content.objects:
TypeError: 'AIOGithubRepositoryContent' object is not iterable
```

**Comment by lambtho12** [comment]
I also have a similar issue. When I click on the "community" tab, I only have the message "background task running" and I only see HACS listed under Integration (there should be many more normally).

Here are the Hassio logs:
```
2019-09-21 17:24:19 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 154, in startup_tasks
    await self.load_known_repositories()
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 283, in load_known_repositories
    await self.register_repository(repo, category)
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 131, in register_repository
    await repository.registration()
  File "/config/custom_components/hacs/repositories/integration.py", line 81, in registration
    if not await self.validate_repository():
  File "/config/custom_components/hacs/repositories/integration.py", line 66, in validate_repository
    for filename in self.content.objects:
TypeError: 'AIOGithubRepositoryContent' object is not iterable
```

**Comment by ludeeus** [comment]
This <https://github.com/fondberg/spotcast/blob/v2.1/custom_components/.DS_Store> file(?) breaks it.
I have blacklisted that repository until I have a proper fix for it, if you restart HA now, everything should be as expected.

**Comment by Red-M** [comment]
Yeah that is an OSX file.

**Comment by ludeeus** [comment]
I'll remove that file from the blacklist tomorrow.
0.14.2 solves it.

**Comment by Red-M** [comment]
I still receive the same error when scanning the repository and viewing that integration.
