### ISSUE TITLE
Network (communication with GitHub) error

### ISSUE THREAD

**Issue by DMQ8** [custom-components/hacs#573]
## Version of HACS
0.14.2

## Describe the bug
I still getting Errors when installing HACS, my first report was related to Home Assistant V0.97.2 and HACS V0.13.2: https://github.com/custom-components/hacs/issues/468
Im still using Docker on Synology NAS, but now using Home Assistant V0.99.3 with HACS V0.14.2:
arch | x86_64
dev | false
docker | true
hassio | false
os_name | Linux
python_version | 3.7.4
version | 0.99.3
virtualenv | false

Under Community, Overview, Im getting the following msg forever:
"Background task running, this page will reload when it's done."

As this is a new installation there is not much in my configuration.yaml , but the following, is what I have for HACS:
hacs:
token: !secret HACS_github
appdaemon: true
python_script: true
theme: true

I can see Items in store and I can also search, but the "background task" msg never end.

I'm also getting the following events/errors that are related to HACS under Developer Tools>Logs :

Error doing job: Task exception was never retrieved
3:02 AM custom_components/hacs/repositories/integration.py (ERROR)

Giving up get_contents(...) after 5 tries (concurrent.futures._base.TimeoutError)
3:02 AM __main__.py (ERROR)

Setup of hacs is taking over 10 seconds.
2:57 AM __main__.py (WARNING)

## Debug log

```text

2019-09-28 02:56:04 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-09-28 02:56:20 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.0 seconds.
2019-09-28 02:56:20 INFO (MainThread) [homeassistant.setup] Setting up http
2019-09-28 02:56:20 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.0 seconds.
2019-09-28 02:56:20 INFO (MainThread) [homeassistant.setup] Setting up system_log
2019-09-28 02:56:20 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.0 seconds.
2019-09-28 02:56:20 INFO (MainThread) [homeassistant.setup] Setting up recorder
2019-09-28 02:56:22 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 2.3 seconds.
2019-09-28 02:56:22 INFO (MainThread) [homeassistant.setup] Setting up updater
2019-09-28 02:56:22 INFO (MainThread) [homeassistant.setup] Setup of domain updater took 0.0 seconds.
2019-09-28 02:56:22 INFO (SyncWorker_7) [homeassistant.util.package] Attempting install of aiofiles==0.4.0
2019-09-28 02:56:22 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2019-09-28 02:56:22 INFO (MainThread) [homeassistant.setup] Setup of domain lovelace took 0.0 seconds.
2019-09-28 02:56:22 INFO (MainThread) [homeassistant.setup] Setting up sun
2019-09-28 02:56:22 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.1 seconds.
2019-09-28 02:56:23 INFO (MainThread) [homeassistant.setup] Setting up person
2019-09-28 02:56:23 INFO (MainThread) [homeassistant.setup] Setting up group
2019-09-28 02:56:23 INFO (MainThread) [homeassistant.setup] Setup of domain group took 0.0 seconds.
2019-09-28 02:56:23 INFO (MainThread) [homeassistant.setup] Setting up configurator
2019-09-28 02:56:23 INFO (MainThread) [homeassistant.setup] Setup of domain configurator took 0.0 seconds.
2019-09-28 02:56:23 INFO (SyncWorker_18) [homeassistant.loader] Loaded binary_sensor from homeassistant.components.binary_sensor
2019-09-28 02:56:23 INFO (MainThread) [homeassistant.setup] Setting up webhook
2019-09-28 02:56:23 INFO (MainThread) [homeassistant.setup] Setup of domain webhook took 0.0 seconds.
2019-09-28 02:56:23 INFO (MainThread) [homeassistant.setup] Setting up auth
2019-09-28 02:56:23 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.0 seconds.
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setting up api
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setting up config
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setting up history
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setup of domain history took 0.0 seconds.
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.0 seconds.
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setting up system_health
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.0 seconds.
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setting up script
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.0 seconds.
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setting up binary_sensor
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setup of domain binary_sensor took 0.0 seconds.
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.1 seconds.
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setting up device_automation
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setup of domain device_automation took 0.0 seconds.
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setting up onboarding
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.1 seconds.
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.updater
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setting up automation
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 0.0 seconds.
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setup of domain onboarding took 0.0 seconds.
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.updater entity: binary_sensor.updater
2019-09-28 02:56:24 INFO (MainThread) [homeassistant.setup] Setup of domain person took 1.3 seconds.
2019-09-28 02:56:35 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of aiogithubapi==0.4.2
2019-09-28 02:56:44 INFO (SyncWorker_34) [homeassistant.util.package] Attempting install of integrationhelper==0.2.2
2019-09-28 02:56:55 INFO (MainThread) [homeassistant.setup] Setting up hacs
2019-09-28 02:56:55 INFO (MainThread) [hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 0.14.2
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/hacs/issues
-------------------------------------------------------------------

2019-09-28 02:56:55 INFO (MainThread) [homeassistant.setup] Setting up ssdp
2019-09-28 02:56:55 INFO (MainThread) [homeassistant.setup] Setup of domain ssdp took 0.0 seconds.
2019-09-28 02:56:55 INFO (MainThread) [homeassistant.setup] Setting up met
2019-09-28 02:56:55 INFO (MainThread) [homeassistant.setup] Setup of domain met took 0.0 seconds.
2019-09-28 02:56:55 INFO (MainThread) [homeassistant.setup] Setting up ecobee
2019-09-28 02:56:55 INFO (SyncWorker_24) [homeassistant.loader] Loaded google_translate from homeassistant.components.google_translate
2019-09-28 02:56:55 INFO (SyncWorker_37) [homeassistant.loader] Loaded weather from homeassistant.components.weather
2019-09-28 02:56:55 INFO (MainThread) [homeassistant.setup] Setting up cloud
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setting up mobile_app
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setting up weather
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setup of domain weather took 0.0 seconds.
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setting up zeroconf
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setup of domain ecobee took 2.1 seconds.
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.components.weather] Setting up weather.met
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setting up frontend
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setup of domain frontend took 0.0 seconds.
2019-09-28 02:56:57 INFO (SyncWorker_4) [homeassistant.loader] Loaded climate from homeassistant.components.climate
2019-09-28 02:56:57 INFO (SyncWorker_26) [homeassistant.loader] Loaded sensor from homeassistant.components.sensor
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setting up tts
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.ecobee
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.components.weather] Setting up weather.ecobee
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setup of domain mobile_app took 0.2 seconds.
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setting up climate
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setup of domain climate took 0.0 seconds.
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setting up sensor
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 0.0 seconds.
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setting up map
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setup of domain map took 0.0 seconds.
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setting up logbook
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setup of domain logbook took 0.0 seconds.
2019-09-28 02:56:57 INFO (SyncWorker_31) [homeassistant.loader] Loaded notify from homeassistant.components.notify
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.components.climate] Setting up climate.ecobee
2019-09-28 02:56:57 INFO (SyncWorker_8) [homeassistant.components.ecobee.climate] Loading ecobee thermostat component with hold_temp set to False
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.ecobee
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setting up notify
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setup of domain notify took 0.0 seconds.
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setup of domain tts took 0.2 seconds.
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.components.notify] Setting up notify.mobile_app
2019-09-28 02:56:57 INFO (MainThread) [homeassistant.setup] Setup of domain cloud took 1.9 seconds.
2019-09-28 02:56:57 INFO (SyncWorker_26) [homeassistant.loader] Loaded heos from homeassistant.components.heos
2019-09-28 02:56:58 INFO (MainThread) [homeassistant.setup] Setup of domain zeroconf took 0.8 seconds.
2019-09-28 02:56:58 INFO (SyncWorker_28) [homeassistant.loader] Loaded cast from homeassistant.components.cast
2019-09-28 02:57:00 INFO (MainThread) [homeassistant.setup] Setting up default_config
2019-09-28 02:57:00 INFO (SyncWorker_38) [homeassistant.loader] Loaded stream from homeassistant.components.stream
2019-09-28 02:57:00 INFO (SyncWorker_37) [homeassistant.loader] Loaded hue from homeassistant.components.hue
2019-09-28 02:57:00 INFO (SyncWorker_36) [homeassistant.loader] Loaded homekit_controller from homeassistant.components.homekit_controller
2019-09-28 02:57:00 INFO (MainThread) [backoff] Backing off get_ratelimit(...) for 0.0s (concurrent.futures._base.TimeoutError)
2019-09-28 02:57:00 INFO (MainThread) [homeassistant.setup] Setting up stream
2019-09-28 02:57:00 INFO (MainThread) [homeassistant.setup] Setup of domain stream took 0.0 seconds.
2019-09-28 02:57:00 INFO (MainThread) [homeassistant.setup] Setup of domain default_config took 0.6 seconds.
2019-09-28 02:57:00 INFO (MainThread) [homeassistant.components.hue] Invalid authentication for 192.168.1.4, requesting link.
2019-09-28 02:57:05 WARNING (MainThread) [homeassistant.setup] Setup of hacs is taking over 10 seconds.
2019-09-28 02:57:05 INFO (MainThread) [hacs.repository.integration.custom-components.hacs] Registration complete
2019-09-28 02:57:05 INFO (MainThread) [homeassistant.setup] Setup of domain hacs took 10.3 seconds.
2019-09-28 02:57:05 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hacs
2019-09-28 02:57:05 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 61.46s
2019-09-28 02:57:05 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2019-09-28 02:57:05 INFO (MainThread) [hacs] Loading known repositories
2019-09-28 02:57:05 INFO (MainThread) [homeassistant.core] Timer:starting
2019-09-28 02:57:13 INFO (MainThread) [hacs.repository.appdaemon.apop880.SmartThings-Button] Registration complete
2019-09-28 02:57:15 INFO (SyncWorker_29) [homeassistant.loader] Loaded rainmachine from homeassistant.components.rainmachine
2019-09-28 02:57:15 INFO (SyncWorker_26) [homeassistant.loader] Loaded twilio from homeassistant.components.twilio
2019-09-28 02:57:15 INFO (SyncWorker_21) [homeassistant.loader] Loaded iaqualink from homeassistant.components.iaqualink
2019-09-28 02:57:15 INFO (SyncWorker_18) [homeassistant.loader] Loaded withings from homeassistant.components.withings
2019-09-28 02:57:15 INFO (SyncWorker_15) [homeassistant.loader] Loaded daikin from homeassistant.components.daikin
2019-09-28 02:57:15 INFO (SyncWorker_10) [homeassistant.loader] Loaded ps4 from homeassistant.components.ps4
2019-09-28 02:57:15 INFO (SyncWorker_14) [homeassistant.loader] Loaded zha from homeassistant.components.zha
2019-09-28 02:57:15 INFO (SyncWorker_12) [homeassistant.loader] Loaded homematicip_cloud from homeassistant.components.homematicip_cloud
2019-09-28 02:57:15 INFO (SyncWorker_12) [homeassistant.loader] Loaded mailgun from homeassistant.components.mailgun
2019-09-28 02:57:15 INFO (SyncWorker_4) [homeassistant.loader] Loaded upnp from homeassistant.components.upnp
2019-09-28 02:57:15 INFO (SyncWorker_7) [homeassistant.loader] Loaded esphome from homeassistant.components.esphome
2019-09-28 02:57:15 INFO (SyncWorker_1) [homeassistant.loader] Loaded zwave from homeassistant.components.zwave
2019-09-28 02:57:15 INFO (SyncWorker_11) [homeassistant.loader] Loaded somfy from homeassistant.components.somfy
2019-09-28 02:57:15 INFO (SyncWorker_27) [homeassistant.loader] Loaded sonos from homeassistant.components.sonos
2019-09-28 02:57:15 INFO (SyncWorker_36) [homeassistant.loader] Loaded tellduslive from homeassistant.components.tellduslive
2019-09-28 02:57:15 INFO (SyncWorker_31) [homeassistant.loader] Loaded toon from homeassistant.components.toon
2019-09-28 02:57:15 INFO (SyncWorker_32) [homeassistant.loader] Loaded ifttt from homeassistant.components.ifttt
2019-09-28 02:57:15 INFO (SyncWorker_39) [homeassistant.loader] Loaded owntracks from homeassistant.components.owntracks
2019-09-28 02:57:15 INFO (SyncWorker_30) [homeassistant.loader] Loaded adguard from homeassistant.components.adguard
2019-09-28 02:57:15 INFO (SyncWorker_25) [homeassistant.loader] Loaded logi_circle from homeassistant.components.logi_circle
2019-09-28 02:57:15 INFO (SyncWorker_24) [homeassistant.loader] Loaded ios from homeassistant.components.ios
2019-09-28 02:57:15 INFO (SyncWorker_29) [homeassistant.loader] Loaded emulated_roku from homeassistant.components.emulated_roku
2019-09-28 02:57:15 INFO (SyncWorker_26) [homeassistant.loader] Loaded traccar from homeassistant.components.traccar
2019-09-28 02:57:15 INFO (SyncWorker_21) [homeassistant.loader] Loaded unifi from homeassistant.components.unifi
2019-09-28 02:57:15 INFO (SyncWorker_18) [homeassistant.loader] Loaded locative from homeassistant.components.locative
2019-09-28 02:57:15 INFO (SyncWorker_15) [homeassistant.loader] Loaded solaredge from homeassistant.components.solaredge
2019-09-28 02:57:15 INFO (SyncWorker_10) [homeassistant.loader] Loaded hangouts from homeassistant.components.hangouts
2019-09-28 02:57:15 INFO (SyncWorker_14) [homeassistant.loader] Loaded vesync from homeassistant.components.vesync
2019-09-28 02:57:15 INFO (SyncWorker_9) [homeassistant.loader] Loaded velbus from homeassistant.components.velbus
2019-09-28 02:57:15 INFO (SyncWorker_5) [homeassistant.loader] Loaded lifx from homeassistant.components.lifx
2019-09-28 02:57:15 INFO (SyncWorker_7) [homeassistant.loader] Loaded mqtt from homeassistant.components.mqtt
2019-09-28 02:57:15 INFO (SyncWorker_2) [homeassistant.loader] Loaded geofency from homeassistant.components.geofency
2019-09-28 02:57:15 INFO (SyncWorker_3) [homeassistant.loader] Loaded nest from homeassistant.components.nest
2019-09-28 02:57:15 INFO (SyncWorker_35) [homeassistant.loader] Loaded twentemilieu from homeassistant.components.twentemilieu
2019-09-28 02:57:15 INFO (SyncWorker_33) [homeassistant.loader] Loaded wemo from homeassistant.components.wemo
2019-09-28 02:57:15 INFO (SyncWorker_38) [homeassistant.loader] Loaded dialogflow from homeassistant.components.dialogflow
2019-09-28 02:57:15 INFO (SyncWorker_20) [homeassistant.loader] Loaded openuv from homeassistant.components.openuv
2019-09-28 02:57:15 INFO (SyncWorker_37) [homeassistant.loader] Loaded axis from homeassistant.components.axis
2019-09-28 02:57:15 INFO (SyncWorker_34) [homeassistant.loader] Loaded notion from homeassistant.components.notion
2019-09-28 02:57:15 INFO (SyncWorker_28) [homeassistant.loader] Loaded ambient_station from homeassistant.components.ambient_station
2019-09-28 02:57:15 INFO (SyncWorker_23) [homeassistant.loader] Loaded plaato from homeassistant.components.plaato
2019-09-28 02:57:15 INFO (SyncWorker_22) [homeassistant.loader] Loaded zone from homeassistant.components.zone
2019-09-28 02:57:15 INFO (SyncWorker_19) [homeassistant.loader] Loaded geonetnz_quakes from homeassistant.components.geonetnz_quakes
2019-09-28 02:57:15 INFO (SyncWorker_17) [homeassistant.loader] Loaded linky from homeassistant.components.linky
2019-09-28 02:57:15 INFO (SyncWorker_13) [homeassistant.loader] Loaded deconz from homeassistant.components.deconz
2019-09-28 02:57:15 INFO (SyncWorker_16) [homeassistant.loader] Loaded ambiclimate from homeassistant.components.ambiclimate
2019-09-28 02:57:15 INFO (SyncWorker_8) [homeassistant.loader] Loaded point from homeassistant.components.point
2019-09-28 02:57:15 INFO (SyncWorker_6) [homeassistant.loader] Loaded gpslogger from homeassistant.components.gpslogger
2019-09-28 02:57:15 INFO (SyncWorker_12) [homeassistant.loader] Loaded ipma from homeassistant.components.ipma
2019-09-28 02:57:15 INFO (SyncWorker_4) [homeassistant.loader] Loaded wwlln from homeassistant.components.wwlln
2019-09-28 02:57:15 INFO (SyncWorker_0) [homeassistant.loader] Loaded luftdaten from homeassistant.components.luftdaten
2019-09-28 02:57:15 INFO (SyncWorker_1) [homeassistant.loader] Loaded smartthings from homeassistant.components.smartthings
2019-09-28 02:57:15 INFO (SyncWorker_11) [homeassistant.loader] Loaded life360 from homeassistant.components.life360
2019-09-28 02:57:15 INFO (SyncWorker_27) [homeassistant.loader] Loaded simplisafe from homeassistant.components.simplisafe
2019-09-28 02:57:15 INFO (SyncWorker_36) [homeassistant.loader] Loaded smhi from homeassistant.components.smhi
2019-09-28 02:57:15 INFO (SyncWorker_31) [homeassistant.loader] Loaded cert_expiry from homeassistant.components.cert_expiry
2019-09-28 02:57:15 INFO (SyncWorker_32) [homeassistant.loader] Loaded tradfri from homeassistant.components.tradfri
2019-09-28 02:57:15 INFO (SyncWorker_39) [homeassistant.loader] Loaded tplink from homeassistant.components.tplink
2019-09-28 02:57:15 INFO (SyncWorker_30) [homeassistant.loader] Loaded iqvia from homeassistant.components.iqvia
2019-09-28 02:57:16 INFO (MainThread) [hacs.repository.appdaemon.apop880.White-Noise] Registration complete
2019-09-28 02:57:18 INFO (MainThread) [hacs.repository.appdaemon.apop880.Night-Mode] Registration complete
2019-09-28 02:57:21 INFO (MainThread) [hacs.repository.appdaemon.apop880.config-check] Registration complete
2019-09-28 02:57:23 INFO (MainThread) [hacs.repository.appdaemon.benleb.ad-automoli] Registration complete
2019-09-28 02:57:26 INFO (MainThread) [hacs.repository.appdaemon.benleb.ad-batterycheck] Registration complete
2019-09-28 02:57:28 INFO (MainThread) [hacs.repository.appdaemon.benleb.ad-healthcheck] Registration complete
2019-09-28 02:57:31 INFO (MainThread) [hacs.repository.appdaemon.benleb.ad-notifreeze] Registration complete
2019-09-28 02:57:33 INFO (MainThread) [hacs.repository.appdaemon.bieniu.ha-ad-airly] Registration complete
2019-09-28 02:57:36 INFO (MainThread) [hacs.repository.appdaemon.bieniu.ha-ad-thermostats-update] Registration complete
2019-09-28 02:57:39 INFO (MainThread) [hacs.repository.appdaemon.ludeeus.ad-watchdog] Registration complete
2019-09-28 02:57:41 INFO (MainThread) [hacs.repository.appdaemon.eifinger.appdaemon-deconz-xiaomi-button] Registration complete
2019-09-28 02:57:45 INFO (MainThread) [hacs.repository.integration.daenny.climate_group] Registration complete
2019-09-28 02:57:48 INFO (MainThread) [hacs.repository.integration.DSorlov.hasl-platform] Registration complete
2019-09-28 02:57:52 INFO (MainThread) [hacs.repository.integration.StyraHem.ShellyForHASS] Registration complete
2019-09-28 02:57:55 INFO (MainThread) [hacs.repository.integration.isabellaalstrom.sensor.krisinformation] Registration complete
2019-09-28 02:57:59 INFO (MainThread) [hacs.repository.integration.JurajNyiri.HomeAssistant-Tavos] Registration complete
2019-09-28 02:58:03 INFO (MainThread) [hacs.repository.integration.JurajNyiri.HomeAssistant-Atrea] Registration complete
2019-09-28 02:58:07 INFO (MainThread) [hacs.repository.integration.JurajNyiri.HomeAssistant-qBitTorrentAlternativeSpeed] Registration complete
2019-09-28 02:58:10 INFO (MainThread) [hacs.repository.integration.TimSoethout.goodwe-sems-home-assistant] Registration complete
2019-09-28 02:58:14 INFO (MainThread) [hacs.repository.integration.bramkragten.lyric] Registration complete
2019-09-28 02:58:17 INFO (MainThread) [hacs.repository.integration.bramkragten.mind] Registration complete
2019-09-28 02:58:21 INFO (MainThread) [hacs.repository.integration.bouwew.sems2mqtt] Registration complete
2019-09-28 02:58:25 INFO (MainThread) [hacs.repository.integration.akasma74.Hass-Custom-Alarm] Registration complete
2019-09-28 02:58:28 INFO (MainThread) [hacs.repository.integration.albertogeniola.meross-homeassistant] Registration complete
2019-09-28 02:58:32 INFO (MainThread) [hacs.repository.integration.mudape.iphonedetect] Registration complete
2019-09-28 02:58:35 INFO (MainThread) [hacs.repository.integration.bertbert72.HomeAssistant_VirginTivo] Registration complete
2019-09-28 02:58:39 INFO (MainThread) [hacs.repository.integration.nstrelow.ha_philips_android_tv] Registration complete
2019-09-28 02:58:43 INFO (MainThread) [hacs.repository.integration.rsnodgrass.hass-integrations] Registration complete
2019-09-28 02:58:46 INFO (MainThread) [hacs.repository.integration.Ceerbeerus.beerbolaget] Registration complete
2019-09-28 02:58:50 INFO (MainThread) [hacs.repository.integration.thomasloven.hass-browser_mod] Registration complete
2019-09-28 02:58:53 INFO (MainThread) [hacs.repository.integration.thomasloven.hass-lovelace_gen] Registration complete
2019-09-28 02:58:57 INFO (MainThread) [hacs.repository.integration.thomasloven.hass-favicon] Registration complete
2019-09-28 02:59:01 INFO (MainThread) [hacs.repository.integration.claytonjn.hass-circadian_lighting] Registration complete
2019-09-28 02:59:05 INFO (MainThread) [hacs.repository.integration.xMrVizzy.Philips-AirPurifier] Registration complete
2019-09-28 02:59:08 INFO (MainThread) [hacs.repository.integration.jomwells.ambilights] Registration complete
2019-09-28 02:59:12 INFO (MainThread) [hacs.repository.integration.jomwells.ambihue] Registration complete
2019-09-28 02:59:15 INFO (MainThread) [hacs.repository.integration.jomwells.ambilight-yeelight] Registration complete
2019-09-28 02:59:19 INFO (MainThread) [hacs.repository.integration.MatthewFlamm.nwsradar] Registration complete
2019-09-28 02:59:22 INFO (MainThread) [hacs.repository.integration.Paul-dH.Home-Assisant-Sensor-OvApi] Registration complete
2019-09-28 02:59:26 INFO (MainThread) [hacs.repository.integration.rt400.School-Vacation] Registration complete
2019-09-28 02:59:30 INFO (MainThread) [hacs.repository.integration.xirixiz.Home-Assistant-Sensor-Afvalwijzer] Registration complete
2019-09-28 02:59:33 INFO (MainThread) [hacs.repository.integration.bieniu.ha-airly] Registration complete
2019-09-28 02:59:37 INFO (MainThread) [hacs.repository.integration.bieniu.ha-gios] Registration complete
2019-09-28 02:59:41 INFO (MainThread) [hacs.repository.integration.DavidFW1960.bom_forecast] Registration complete
2019-09-28 02:59:45 INFO (MainThread) [hacs.repository.integration.legrego.homeassistant-elasticsearch] Registration complete
2019-09-28 02:59:48 INFO (MainThread) [hacs.repository.integration.kalanda.homeassistant-aemet-sensor] Registration complete
2019-09-28 02:59:52 INFO (MainThread) [hacs.repository.integration.basschipper.homeassistant-generic-hygrostat] Registration complete
2019-09-28 02:59:55 INFO (MainThread) [hacs.repository.integration.claudegel.sinope-1] Registration complete
2019-09-28 02:59:59 INFO (MainThread) [hacs.repository.integration.claudegel.sinope-gt125] Registration complete
2019-09-28 03:00:03 INFO (MainThread) [hacs.repository.integration.tybritten.ical-sensor-homeassistant] Registration complete
2019-09-28 03:00:07 INFO (MainThread) [hacs.repository.integration.Martinvdm.garbage-nissewaard-homeassistant] Registration complete
2019-09-28 03:00:11 INFO (MainThread) [hacs.repository.integration.RobHofmann.HomeAssistant-GreeClimateComponent] Registration complete
2019-09-28 03:00:14 INFO (MainThread) [hacs.repository.integration.pippyn.Home-Assistant-Sensor-Afvalbeheer] Registration complete
2019-09-28 03:00:18 INFO (MainThread) [hacs.repository.integration.pippyn.Home-Assistant-Sensor-Groningen-Afvalwijzer] Registration complete
2019-09-28 03:00:41 INFO (MainThread) [backoff] Backing off get_contents(...) for 0.2s (concurrent.futures._base.TimeoutError)
2019-09-28 03:00:46 INFO (MainThread) [backoff] Backing off get_ratelimit(...) for 0.6s (concurrent.futures._base.TimeoutError)
2019-09-28 03:01:08 INFO (MainThread) [backoff] Backing off get_contents(...) for 0.8s (concurrent.futures._base.TimeoutError)
2019-09-28 03:01:30 INFO (MainThread) [backoff] Backing off get_contents(...) for 2.5s (concurrent.futures._base.TimeoutError)
2019-09-28 03:01:54 INFO (MainThread) [backoff] Backing off get_contents(...) for 8.0s (concurrent.futures._base.TimeoutError)
2019-09-28 03:02:24 ERROR (MainThread) [backoff] Giving up get_contents(...) after 5 tries (concurrent.futures._base.TimeoutError)
2019-09-28 03:02:24 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiogithubapi/repository.py", line 90, in get_contents
    response = await self.session.get(url, headers=self.headers, params=params)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 497, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 844, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 588, in read
    await self._waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 154, in startup_tasks
    await self.load_known_repositories()
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 283, in load_known_repositories
    await self.register_repository(repo, category)
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 131, in register_repository
    await repository.registration()
  File "/config/custom_components/hacs/repositories/integration.py", line 84, in registration
    if not await self.validate_repository():
  File "/config/custom_components/hacs/repositories/integration.py", line 72, in validate_repository
    if not await self.get_manifest():
  File "/config/custom_components/hacs/repositories/integration.py", line 142, in get_manifest
    manifest = await self.repository_object.get_contents(manifest_path, self.ref)
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aiogithubapi/repository.py", line 108, in get_contents
    contents.append(AIOGithubRepositoryContent(content))
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

```

Thanks.

**Comment by ludeeus** [comment]
This is most likely an issue with the amount of traffic and how Synology does networking.

Unzip this:
[hacs.zip](https://github.com/custom-components/hacs/files/3665172/hacs.zip)

It will give you 3 files, move those to inside your `.storage` directory, then restart HA.
