### ISSUE TITLE
Python 3.5 & Xiaomi gateway Event loop closed

### ISSUE THREAD

**Issue by AntoWkill** [custom-components/hacs#574]
Hello,
I tried to install HACS but after that my homeassistant don't start.

I thinks that is problem with Xioami Gateway.

Version HA: 0.9.2
Version HACS: 0.14.2

### Debug
```

root@raspberrypi:~/.homeassistant# service hass start
tail -f homeroot@raspberrypi:~/.homeassistant# tail -f home-assistant.log
2019-09-28 14:47:04 WARNING (MainThread) [homeassistant.helpers.config_validation] Found invalid entity_id sensor.active_power__phase_1, please update with sensor.active_power_phase_1. This will become a breaking change.
2019-09-28 14:47:05 INFO (Thread-11) [homeassistant.loader] Loaded hacs from custom_components.hacs
2019-09-28 14:47:05 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-09-28 14:47:05 INFO (Thread-6) [homeassistant.loader] Loaded upnp from homeassistant.components.upnp
2019-09-28 14:47:05 INFO (Thread-13) [homeassistant.loader] Loaded history from homeassistant.components.history
2019-09-28 14:47:05 INFO (Thread-7) [homeassistant.loader] Loaded frontend from homeassistant.components.frontend
2019-09-28 14:47:05 INFO (Thread-16) [homeassistant.loader] Loaded xiaomi_aqara from homeassistant.components.xiaomi_aqara
2019-09-28 14:47:05 INFO (Thread-5) [homeassistant.loader] Loaded script from homeassistant.components.script
2019-09-28 14:47:05 INFO (Thread-2) [homeassistant.loader] Loaded updater from homeassistant.components.updater
2019-09-28 14:47:05 INFO (Thread-19) [homeassistant.loader] Loaded switch from homeassistant.components.switch
2019-09-28 14:47:05 INFO (Thread-6) [homeassistant.loader] Loaded ifttt from homeassistant.components.ifttt
2019-09-28 14:47:05 INFO (Thread-21) [homeassistant.loader] Loaded zwave from homeassistant.components.zwave
2019-09-28 14:47:05 INFO (Thread-9) [homeassistant.loader] Loaded zone from homeassistant.components.zone
2019-09-28 14:47:05 INFO (Thread-13) [homeassistant.loader] Loaded weather from homeassistant.components.weather
2019-09-28 14:47:05 INFO (Thread-18) [homeassistant.loader] Loaded config from homeassistant.components.config
2019-09-28 14:47:05 INFO (Thread-14) [homeassistant.loader] Loaded discovery from homeassistant.components.discovery
2019-09-28 14:47:05 INFO (Thread-3) [homeassistant.loader] Loaded automation from homeassistant.components.automation
2019-09-28 14:47:05 INFO (Thread-8) [homeassistant.loader] Loaded cloud from homeassistant.components.cloud
2019-09-28 14:47:05 INFO (Thread-12) [homeassistant.loader] Loaded api from homeassistant.components.api
2019-09-28 14:47:05 INFO (Thread-15) [homeassistant.loader] Loaded alexa from homeassistant.components.alexa
2019-09-28 14:47:05 INFO (Thread-10) [homeassistant.loader] Loaded homekit from homeassistant.components.homekit
2019-09-28 14:47:05 INFO (Thread-11) [homeassistant.loader] Loaded logbook from homeassistant.components.logbook
2019-09-28 14:47:05 INFO (Thread-7) [homeassistant.loader] Loaded group from homeassistant.components.group
2019-09-28 14:47:05 INFO (Thread-4) [homeassistant.loader] Loaded conversation from homeassistant.components.conversation
2019-09-28 14:47:05 INFO (Thread-20) [homeassistant.loader] Loaded sensor from homeassistant.components.sensor
2019-09-28 14:47:05 INFO (Thread-2) [homeassistant.loader] Loaded media_player from homeassistant.components.media_player
2019-09-28 14:47:05 INFO (Thread-5) [homeassistant.loader] Loaded recorder from homeassistant.components.recorder
2019-09-28 14:47:05 INFO (Thread-6) [homeassistant.loader] Loaded light from homeassistant.components.light
2019-09-28 14:47:05 INFO (Thread-19) [homeassistant.loader] Loaded climate from homeassistant.components.climate
2019-09-28 14:47:05 INFO (Thread-16) [homeassistant.loader] Loaded sun from homeassistant.components.sun
2019-09-28 14:47:05 INFO (Thread-13) [homeassistant.loader] Loaded notify from homeassistant.components.notify
2019-09-28 14:47:05 INFO (Thread-21) [homeassistant.loader] Loaded google_assistant from homeassistant.components.google_assistant
2019-09-28 14:47:05 INFO (Thread-9) [homeassistant.loader] Loaded http from homeassistant.components.http
2019-09-28 14:47:05 INFO (Thread-3) [homeassistant.loader] Loaded mqtt from homeassistant.components.mqtt
2019-09-28 14:47:05 INFO (Thread-14) [homeassistant.loader] Loaded cast from homeassistant.components.cast
2019-09-28 14:47:05 INFO (Thread-18) [homeassistant.loader] Loaded mobile_app from homeassistant.components.mobile_app
2019-09-28 14:47:05 INFO (Thread-17) [homeassistant.loader] Loaded ios from homeassistant.components.ios
2019-09-28 14:47:05 INFO (Thread-8) [homeassistant.loader] Loaded tts from homeassistant.components.tts
2019-09-28 14:47:05 INFO (Thread-15) [homeassistant.loader] Loaded panel_iframe from homeassistant.components.panel_iframe
2019-09-28 14:47:05 INFO (Thread-10) [homeassistant.loader] Loaded persistent_notification from homeassistant.components.persistent_notification
2019-09-28 14:47:05 INFO (Thread-12) [homeassistant.loader] Loaded homeassistant from homeassistant.components.homeassistant
2019-09-28 14:47:05 INFO (Thread-11) [homeassistant.loader] Loaded map from homeassistant.components.map
2019-09-28 14:47:05 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for enigma which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-09-28 14:47:05 INFO (MainThread) [homeassistant.loader] Loaded enigma from custom_components.enigma
2019-09-28 14:47:05 INFO (MainThread) [homeassistant.setup] Setting up persistent_notification
2019-09-28 14:47:05 INFO (MainThread) [homeassistant.setup] Setup of domain persistent_notification took 0.0 seconds.
2019-09-28 14:47:05 INFO (MainThread) [homeassistant.setup] Setting up homeassistant
2019-09-28 14:47:05 INFO (MainThread) [homeassistant.setup] Setup of domain homeassistant took 0.0 seconds.
2019-09-28 14:47:05 INFO (Thread-5) [homeassistant.loader] Loaded device_tracker from homeassistant.components.device_tracker
2019-09-28 14:47:05 INFO (Thread-6) [homeassistant.loader] Loaded auth from homeassistant.components.auth
2019-09-28 14:47:05 INFO (Thread-2) [homeassistant.loader] Loaded webhook from homeassistant.components.webhook
2019-09-28 14:47:05 INFO (Thread-13) [homeassistant.loader] Loaded zeroconf from homeassistant.components.zeroconf
2019-09-28 14:47:05 INFO (Thread-21) [homeassistant.loader] Loaded lovelace from homeassistant.components.lovelace
2019-09-28 14:47:05 INFO (Thread-3) [homeassistant.loader] Loaded onboarding from homeassistant.components.onboarding
2019-09-28 14:47:05 INFO (Thread-18) [homeassistant.loader] Loaded system_log from homeassistant.components.system_log
2019-09-28 14:47:05 INFO (Thread-8) [homeassistant.loader] Loaded websocket_api from homeassistant.components.websocket_api
2019-09-28 14:47:05 INFO (MainThread) [homeassistant.bootstrap] Setting up {'system_log'}
2019-09-28 14:47:05 WARNING (MainThread) [homeassistant.components.http] Configuring api_password via the http component has been deprecated. Use the legacy api password auth provider instead. For instructions, see https://www.home-assistant.io/docs/authentication/providers/#legacy-api-password
2019-09-28 14:47:05 INFO (MainThread) [homeassistant.setup] Setting up http
2019-09-28 14:47:05 WARNING (MainThread) [homeassistant.components.http.auth] legacy_api_password support has been enabled.
2019-09-28 14:47:05 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.0 seconds.
2019-09-28 14:47:05 INFO (MainThread) [homeassistant.setup] Setting up system_log
2019-09-28 14:47:05 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.0 seconds.
2019-09-28 14:47:05 INFO (MainThread) [homeassistant.setup] Setting up recorder
2019-09-28 14:47:06 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=76 from 2019-09-28 12:39:49.190995)
2019-09-28 14:47:06 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 1.1 seconds.
2019-09-28 14:47:06 INFO (MainThread) [homeassistant.setup] Setting up notify
2019-09-28 14:47:06 INFO (MainThread) [homeassistant.setup] Setting up sun
2019-09-28 14:47:06 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.1 seconds.
2019-09-28 14:47:06 INFO (MainThread) [homeassistant.setup] Setting up zone
2019-09-28 14:47:06 INFO (MainThread) [homeassistant.setup] Setup of domain zone took 0.0 seconds.
2019-09-28 14:47:06 INFO (MainThread) [homeassistant.setup] Setting up upnp
2019-09-28 14:47:06 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2019-09-28 14:47:06 INFO (MainThread) [homeassistant.setup] Setup of domain lovelace took 0.0 seconds.
2019-09-28 14:47:06 INFO (MainThread) [homeassistant.setup] Setting up enigma
2019-09-28 14:47:06 INFO (MainThread) [custom_components.enigma] Initializing enigma devices
2019-09-28 14:47:06 INFO (MainThread) [homeassistant.setup] Setup of domain enigma took 0.0 seconds.
2019-09-28 14:47:06 INFO (MainThread) [homeassistant.setup] Setting up discovery
2019-09-28 14:47:07 INFO (MainThread) [homeassistant.setup] Setup of domain discovery took 0.4 seconds.
2019-09-28 14:47:07 INFO (MainThread) [homeassistant.setup] Setting up updater
2019-09-28 14:47:07 INFO (MainThread) [homeassistant.setup] Setting up zwave
2019-09-28 14:47:07 INFO (MainThread) [homeassistant.setup] Setup of domain zwave took 0.0 seconds.
2019-09-28 14:47:08 INFO (MainThread) [homeassistant.components.zwave] Z-Wave USB path is /dev/ttyACM0
2019-09-28 14:47:08 WARNING (MainThread) [homeassistant.helpers.config_validation] Found invalid entity_id sensor.time__date, please update with sensor.time_date. This will become a breaking change.
2019-09-28 14:47:08 INFO (MainThread) [homeassistant.setup] Setting up group
2019-09-28 14:47:08 INFO (MainThread) [homeassistant.setup] Setting up xiaomi_aqara
2019-09-28 14:47:08 INFO (MainThread) [homeassistant.setup] Setting up cast
2019-09-28 14:47:08 INFO (MainThread) [homeassistant.setup] Setup of domain cast took 0.0 seconds.
2019-09-28 14:47:08 INFO (MainThread) [homeassistant.setup] Setting up homekit
2019-09-28 14:47:08 INFO (MainThread) [homeassistant.components.notify] Setting up notify.enigma
2019-09-28 14:47:08 INFO (MainThread) [custom_components.enigma] [Enigma Notify] Enigma receiver at host 192.168.1.108 initialized
2019-09-28 14:47:08 INFO (MainThread) [homeassistant.setup] Setup of domain upnp took 1.5 seconds.
2019-09-28 14:47:08 INFO (Thread-6) [homeassistant.components.xiaomi_aqara] Discovering Xiaomi Gateways (Try 1)
2019-09-28 14:47:08 INFO (Thread-6) [xiaomi_gateway] Xiaomi Gateway 7811dcb05fde found at IP 192.168.1.102
2019-09-28 14:47:08 INFO (Thread-6) [xiaomi_gateway] Discovering Xiaomi Devices
2019-09-28 14:47:08 INFO (Thread-6) [xiaomi_gateway] Found 13 devices
2019-09-28 14:47:08 INFO (MainThread) [homeassistant.setup] Setup of domain updater took 1.1 seconds.
2019-09-28 14:47:08 INFO (Thread-13) [homeassistant.loader] Loaded miflora from homeassistant.components.miflora
2019-09-28 14:47:08 INFO (Thread-9) [homeassistant.loader] Loaded yweather from homeassistant.components.yweather
2019-09-28 14:47:08 INFO (Thread-21) [homeassistant.loader] Loaded generic_thermostat from homeassistant.components.generic_thermostat
2019-09-28 14:47:09 INFO (MainThread) [homeassistant.setup] Setting up alexa
2019-09-28 14:47:09 INFO (MainThread) [homeassistant.setup] Setup of domain alexa took 0.0 seconds.
2019-09-28 14:47:09 INFO (MainThread) [homeassistant.setup] Setting up conversation
2019-09-28 14:47:09 INFO (MainThread) [homeassistant.setup] Setup of domain conversation took 0.0 seconds.
2019-09-28 14:47:09 INFO (MainThread) [homeassistant.setup] Setting up api
2019-09-28 14:47:09 INFO (MainThread) [homeassistant.setup] Setting up history
2019-09-28 14:47:09 INFO (MainThread) [homeassistant.setup] Setup of domain history took 0.0 seconds.
2019-09-28 14:47:09 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2019-09-28 14:47:09 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.0 seconds.
2019-09-28 14:47:09 INFO (MainThread) [homeassistant.setup] Setting up config
2019-09-28 14:47:09 INFO (MainThread) [homeassistant.setup] Setting up mqtt
2019-09-28 14:47:09 INFO (MainThread) [homeassistant.setup] Setup of domain mqtt took 0.0 seconds.
2019-09-28 14:47:09 INFO (MainThread) [homeassistant.setup] Setting up auth
2019-09-28 14:47:09 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.0 seconds.
2019-09-28 14:47:09 INFO (MainThread) [homeassistant.setup] Setting up webhook
2019-09-28 14:47:09 INFO (MainThread) [homeassistant.setup] Setup of domain webhook took 0.0 seconds.
2019-09-28 14:47:10 INFO (MainThread) [homeassistant.setup] Setting up google_assistant
2019-09-28 14:47:10 INFO (MainThread) [homeassistant.setup] Setup of domain google_assistant took 0.0 seconds.
2019-09-28 14:47:13 INFO (Thread-6) [xiaomi_gateway] Gateway discovery finished in 5 seconds
2019-09-28 14:47:13 INFO (Thread-6) [xiaomi_gateway] Creating Multicast Socket
2019-09-28 14:47:13 ERROR (Thread-6) [concurrent.futures] exception calling callback for <Future at 0x685a18d0 state=finished raised RuntimeError>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/components/xiaomi_aqara/__init__.py", line 144, in setup
    discovery.load_platform(hass, component, DOMAIN, {}, config)
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/helpers/discovery.py", line 130, in load_platform
    hass_config))
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/core.py", line 246, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 618, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 463, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 618, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-09-28 14:47:40 ERROR (Thread-22) [xiaomi_gateway] Cannot process multicast message: {'model': 'motion', 'short_id': 2181, 'cmd': 'report', 'sid': '158d0001ad43b4', 'data': '{"status":"motion"}'}
2019-09-28 14:49:39 ERROR (Thread-22) [xiaomi_gateway] Cannot process multicast message: {'model': 'motion', 'short_id': 2181, 'cmd': 'report', 'sid': '158d0001ad43b4', 'data': '{"no_motion":"120"}'}

```

Of course when i disable hacs from configuration.yaml all is working again

**Comment by ludeeus** [comment]
You are using python 3.5
That is not supported for ltest HA or HACS, you need to upgrade.
