### ISSUE TITLE
[hacs.repository.integration.danobot.entity-controller] Missing manifest file.

### ISSUE THREAD

**Issue by poudenes** [custom-components/hacs#630]
Hi All,

get this error:

`[hacs.repository.integration.danobot.entity-controller] Missing manifest file.`

Running hassio 0.99.2 on a RPi 3B+ Docker config

**Comment by mgiako** [comment]
me too, 0.93.3 on hassio + nuc 
```
2019-10-06 18:29:45 ERROR (MainThread) [hacs.repository.integration.danobot.entity-controller] Missing manifest file.
2019-10-06 18:29:45 ERROR (MainThread) [hacs] Validation for danobot/entity-controller failed.
```

**Comment by ludeeus** [comment]
Everyone get that, you can ignore it

**Comment by mgiako** [comment]
ok, thanks

**Comment by poudenes** [comment]
Thanks. Add to ignore list in my brain (programming done) 😊

**Comment by Oligarch** [comment]
HA 0.99.3

The same error...

> 2019-10-08 22:20:18 ERROR (MainThread) [hacs.repository.integration.danobot.entity-controller] Missing manifest file.
> 2019-10-08 22:20:18 ERROR (MainThread) [hacs] Validation for danobot/entity-controller failed.

**Comment by GoNzCiD** [comment]
Hi, I have this error too, but I also have this other one that I want to know if its related with?
```log
2019-10-09 09:28:28 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in async_setup_platform
    self.hass, self.config, self.domain, platform_type
  File "/usr/src/homeassistant/homeassistant/setup.py", line 227, in async_prepare_setup_platform
    integration = await loader.async_get_integration(hass, platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 278, in async_get_integration
    Integration.resolve_from_root, hass, components, domain
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 154, in resolve_from_root
    manifest_path = pathlib.Path(base) / domain / "manifest.json"
  File "/usr/local/lib/python3.7/pathlib.py", line 908, in __truediv__
    return self._make_child((key,))
  File "/usr/local/lib/python3.7/pathlib.py", line 695, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python3.7/pathlib.py", line 649, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by ludeeus** [comment]
It is not related

**Comment by ludeeus** [comment]
Closed by https://github.com/danobot/entity-controller/pull/83
