### ISSUE TITLE
No module named 'aiogithubapi'

### ISSUE THREAD

**Issue by gaetanlord** [custom-components/hacs#662]
## Describe the bug
Bare with me, I'm not very efficient with python.

Just upgraded from 0.98.? to hassio 0.100.1 on Ubuntu 18.04.3 LTS. 

HACS 0.13 didn't work anymore, so I decide to upgrade to latest and greatest. I copy over the previous directory the new hacs custom components. HACS didn't start.

I erase the custom_components/hacs directory and copy only the 0.15.5 components, same issue.

In both case, it does report that aiogithubapi is not there.

Not sure if I did a mistake, but I ran the command "pip3 install aiogithubapi", and I got the same issue.

Not sure where to go from here, log output include

Thank you

## Debug log

```text
2019-10-11 21:05:43 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.hacs. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 346, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/__init__.py", line 25, in <module>
    from aiogithubapi import (
ModuleNotFoundError: No module named 'aiogithubapi'
2019-10-11 21:05:43 ERROR (MainThread) [homeassistant.setup] Setup failed for hacs: Integration not found.



```

**Comment by ludeeus** [comment]
You are running docker/hassio, executing pip install does not make a difference.

HA is responsible to install dependencies.
If you are using Hassio, just restart HA a couple of times.
The same applies to docker.

On docker, I have seen the same issue when you have modified the user that the container uses, if that is the case you probably have a log entry stating permission error a few lines up in the log _file_

**Comment by rkoripalli** [comment]
Adding '.' to PYTHONPATH solved this for me.
In my case 
`export PYTHONPATH=.`

**Comment by ludeeus** [comment]
Closing this since there is nothing I can do in the integration about this.
