### ISSUE TITLE
"The frontend of HACS have been disabled until you restart Home Assistant"

### ISSUE THREAD

**Issue by pico563** [custom-components/hacs#663]
@ludeeus ludeeus referenced this issue 6 days ago
> the issue is with the files containing `hacs` in the **`.storage` folder**.
> Delete all hacs files there.

- # where can I find this folder on Hassio??

many user are getting the same problem
so **please stop closing** the issue until we resolve our problems

**Comment by pico563** [comment]
```
2019-10-12 06:23:57 ERROR (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "automation". Check lines 106 and 131.
2019-10-12 06:24:00 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-10-12 06:24:04 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-10-12 06:24:13 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=135 from 2019-10-12 03:48:33.470066)
2019-10-12 06:24:24 WARNING (MainThread) [homeassistant.setup] Setup of person is taking over 10 seconds.
2019-10-12 06:24:39 WARNING (MainThread) [homeassistant.setup] Setup of hacs is taking over 10 seconds.
2019-10-12 06:24:39 WARNING (MainThread) [homeassistant.components.sensor] Setup of platform command_line is taking over 10 seconds.
2019-10-12 06:24:39 WARNING (MainThread) [homeassistant.components.weather] Setup of platform darksky is taking over 10 seconds.
2019-10-12 06:24:43 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/ssdp/__init__.py", line 38, in initialize
    await scanner.async_scan(None)
  File "/usr/src/homeassistant/homeassistant/components/ssdp/__init__.py", line 61, in async_scan
    await self._process_entries(entries)
  File "/usr/src/homeassistant/homeassistant/components/ssdp/__init__.py", line 85, in _process_entries
    result for result in await asyncio.gather(*tasks) if result is not None
  File "/usr/src/homeassistant/homeassistant/components/ssdp/__init__.py", line 124, in _process_entry
    info = await info_req
  File "/usr/src/homeassistant/homeassistant/components/ssdp/__init__.py", line 124, in _process_entry
    info = await info_req
  File "/usr/src/homeassistant/homeassistant/components/ssdp/__init__.py", line 124, in _process_entry
    info = await info_req
  File "/usr/src/homeassistant/homeassistant/components/ssdp/__init__.py", line 139, in _fetch_description
    xml = await resp.text()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1014, in text
    return self._body.decode(encoding, errors=errors)  # type: ignore
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 229: invalid start byte
2019-10-12 06:24:54 CRITICAL (MainThread) [hacs.data] [Expecting value: line 1 column 1 (char 0)] Restore Failed!
2019-10-12 06:24:54 WARNING (MainThread) [homeassistant.components.frontend] Removing unknown panel community
2019-10-12 06:34:19 WARNING (zeroconf-ServiceBrowser__googlecast._tcp.local.) [zeroconf] Exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zeroconf.py", line 2245, in send
    bytes_sent = s.sendto(packet, 0, (addr, port))
PermissionError: [Errno 1] Operation not permitted
2019-10-12 06:39:55 WARNING (MainThread) [homeassistant.components.frontend] Overwriting integration hacs_web
2019-10-12 06:39:55 CRITICAL (MainThread) [hacs.data] [Expecting value: line 1 column 1 (char 0)] Restore Failed!
2019-10-12 06:39:55 WARNING (MainThread) [homeassistant.components.frontend] Removing unknown panel community
2019-10-12 06:54:56 WARNING (MainThread) [homeassistant.components.frontend] Overwriting integration hacs_web
2019-10-12 06:54:56 CRITICAL (MainThread) [hacs.data] [Expecting value: line 1 column 1 (char 0)] Restore Failed!
2019-10-12 06:54:56 WARNING (MainThread) [homeassistant.components.frontend] Removing unknown panel community

```

**Comment by ludeeus** [comment]
`/config/.storage`
