### ISSUE TITLE
Error while loading repositories - recuring_tasks_all

### ISSUE THREAD

**Issue by Misiu** [custom-components/hacs#714]
## Describe the bug
I had working HACS on old HA, now I've set up new Raspberry Pi 3 with HA and I've installed HACS.
But I got no items and the background task was running forever. I've removed files (with hacs is the name) in `.storage`, but that didn't help.

## Debug log

> 2019-10-19 00:49:29 INFO (MainThread) [hacs.api] Loading known repositories
> 2019-10-19 00:49:29 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/config/custom_components/hacs/hacsbase/__init__.py", line 218, in recuring_tasks_all
>     await self.load_known_repositories()
>   File "/config/custom_components/hacs/hacsbase/__init__.py", line 278, in load_known_repositories
>     blacklist = await self.repo.get_contents("repositories/blacklist", "data")
> AttributeError: 'NoneType' object has no attribute 'get_contents'

I've tried the newer version (0.15.7) but without any luck.

**Comment by ludeeus** [comment]
Please enable debug for HACS and post your entire startup log.
<https://hacs.xyz/docs/basic/logs>
