### ISSUE TITLE
Could not install dependencies when using Docker

### ISSUE THREAD

**Issue by simonszu** [custom-components/hacs#733]
## Version of HACS
0.15.11

## Describe the bug
It is not possible to acitvate the HACS integration in Home Assistant when the official docker image is used because of a dependency error. 

## Debug log

```text

2019-10-23 10:37:13 INFO (SyncWorker_6) [homeassistant.util.package] Attempting install of aiofiles==0.4.0
2019-10-23 10:37:28 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package aiofiles==0.4.0: ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/site-packages/aiofiles'
Consider using the `--user` option or check the permissions.

WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
2019-10-23 10:37:28 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 40, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 231, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 128, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 131, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 48, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 60, in post
    handler, context={"source": config_entries.SOURCE_USER}
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 66, in async_init
    flow = await self._async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 626, in _async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 287, in async_process_deps_reqs
    hass, integration.domain, integration.requirements
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 71, in async_process_requirements
    raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for hacs not found: ['aiofiles==0.4.0'].

```

A possible solution would be to modify the official docker image and add the aiofiles via Dockerfile, so that it's available on container start. But maybe there is a better solution, who knows. Maybe mounting an external directory and using pip therein? 

Let's discuss.

**Comment by ludeeus** [comment]
`Permission denied`, you are probably defining a custom user/group in your docker env.
You will get that issue on _any_ custom integration you use that have external libs (most of them do)

When you use the official guide on the HA website to run the container it works.

I don't know enough about this to advise you about a solution.

**Comment by simonszu** [comment]
Yeah, okay, it was indeed a permission error on my file system. Realized it when i found other posts in the HASS forum where people were successfully able to install it with Docker. I was a bit confused at first since HACS installation instructions only mention Python venv and Hassio, so i was wondering if Docker wasn't supported. 

Thanks for reaching out to me, case closed.
